// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// The onexmesh.v1 HTTP extensions let a protobuf service method declare its HTTP
// REST route. The protoc-gen-onexmesh plugin turns each annotated method into a
// generated HTTP route that decodes path/query/body into the request message and
// calls the SAME service implementation used by gRPC, mirroring grpc-gateway's
// google.api.http annotation with a self-contained message.
//
// Extension field numbers live in the reserved custom-option range (>= 50000).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pkg/proto/onexmesh/v1/http.proto

package onexmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HttpRule maps a single RPC method to an HTTP REST endpoint. Exactly one of the
// HTTP verb fields should be set; the path template uses {field} placeholders
// that refer to request message fields, e.g. "/v1/{name}".
type HttpRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// get maps the method to GET with the given path template.
	Get string `protobuf:"bytes,1,opt,name=get,proto3" json:"get,omitempty"`
	// put maps the method to PUT with the given path template.
	Put string `protobuf:"bytes,2,opt,name=put,proto3" json:"put,omitempty"`
	// post maps the method to POST with the given path template.
	Post string `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	// delete maps the method to DELETE with the given path template.
	Delete string `protobuf:"bytes,4,opt,name=delete,proto3" json:"delete,omitempty"`
	// patch maps the method to PATCH with the given path template.
	Patch string `protobuf:"bytes,5,opt,name=patch,proto3" json:"patch,omitempty"`
	// body names the request field used as the HTTP request body, or "*" for the
	// whole request message. Empty means no request body.
	Body          string `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRule) Reset() {
	*x = HttpRule{}
	mi := &file_pkg_proto_onexmesh_v1_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRule) ProtoMessage() {}

func (x *HttpRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_v1_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRule.ProtoReflect.Descriptor instead.
func (*HttpRule) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_v1_http_proto_rawDescGZIP(), []int{0}
}

func (x *HttpRule) GetGet() string {
	if x != nil {
		return x.Get
	}
	return ""
}

func (x *HttpRule) GetPut() string {
	if x != nil {
		return x.Put
	}
	return ""
}

func (x *HttpRule) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *HttpRule) GetDelete() string {
	if x != nil {
		return x.Delete
	}
	return ""
}

func (x *HttpRule) GetPatch() string {
	if x != nil {
		return x.Patch
	}
	return ""
}

func (x *HttpRule) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var file_pkg_proto_onexmesh_v1_http_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpRule)(nil),
		Field:         51236,
		Name:          "onexmesh.v1.http",
		Tag:           "bytes,51236,opt,name=http",
		Filename:      "pkg/proto/onexmesh/v1/http.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// http is the HTTP mapping for a method.
	//
	// optional onexmesh.v1.HttpRule http = 51236;
	E_Http = &file_pkg_proto_onexmesh_v1_http_proto_extTypes[0]
)

var File_pkg_proto_onexmesh_v1_http_proto protoreflect.FileDescriptor

const file_pkg_proto_onexmesh_v1_http_proto_rawDesc = "" +
	"\n" +
	" pkg/proto/onexmesh/v1/http.proto\x12\vonexmesh.v1\x1a google/protobuf/descriptor.proto\"\x84\x01\n" +
	"\bHttpRule\x12\x10\n" +
	"\x03get\x18\x01 \x01(\tR\x03get\x12\x10\n" +
	"\x03put\x18\x02 \x01(\tR\x03put\x12\x12\n" +
	"\x04post\x18\x03 \x01(\tR\x04post\x12\x16\n" +
	"\x06delete\x18\x04 \x01(\tR\x06delete\x12\x14\n" +
	"\x05patch\x18\x05 \x01(\tR\x05patch\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body:K\n" +
	"\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xa4\x90\x03 \x01(\v2\x15.onexmesh.v1.HttpRuleR\x04httpB@Z>github.com/onexstack/onexmesh/pkg/proto/onexmesh/v1;onexmeshv1b\x06proto3"

var (
	file_pkg_proto_onexmesh_v1_http_proto_rawDescOnce sync.Once
	file_pkg_proto_onexmesh_v1_http_proto_rawDescData []byte
)

func file_pkg_proto_onexmesh_v1_http_proto_rawDescGZIP() []byte {
	file_pkg_proto_onexmesh_v1_http_proto_rawDescOnce.Do(func() {
		file_pkg_proto_onexmesh_v1_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_onexmesh_v1_http_proto_rawDesc), len(file_pkg_proto_onexmesh_v1_http_proto_rawDesc)))
	})
	return file_pkg_proto_onexmesh_v1_http_proto_rawDescData
}

var file_pkg_proto_onexmesh_v1_http_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_onexmesh_v1_http_proto_goTypes = []any{
	(*HttpRule)(nil),                   // 0: onexmesh.v1.HttpRule
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_pkg_proto_onexmesh_v1_http_proto_depIdxs = []int32{
	1, // 0: onexmesh.v1.http:extendee -> google.protobuf.MethodOptions
	0, // 1: onexmesh.v1.http:type_name -> onexmesh.v1.HttpRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_onexmesh_v1_http_proto_init() }
func file_pkg_proto_onexmesh_v1_http_proto_init() {
	if File_pkg_proto_onexmesh_v1_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_onexmesh_v1_http_proto_rawDesc), len(file_pkg_proto_onexmesh_v1_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_onexmesh_v1_http_proto_goTypes,
		DependencyIndexes: file_pkg_proto_onexmesh_v1_http_proto_depIdxs,
		MessageInfos:      file_pkg_proto_onexmesh_v1_http_proto_msgTypes,
		ExtensionInfos:    file_pkg_proto_onexmesh_v1_http_proto_extTypes,
	}.Build()
	File_pkg_proto_onexmesh_v1_http_proto = out.File
	file_pkg_proto_onexmesh_v1_http_proto_goTypes = nil
	file_pkg_proto_onexmesh_v1_http_proto_depIdxs = nil
}
