// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// The onexmesh.v1 service-discovery extension lets a .proto file that defines
// gRPC services request generation of a mesh-aware client. The
// protoc-gen-onexmesh-client plugin turns it into a zz_generated.mesh.go with a
// New<Service>MeshClient constructor that discovers the service via the
// onexmesh registry and dials it through pkg/client.
//
// It is a separate extension (50010) so it never interferes with the REST
// options in onexmesh/rest/v1 (50000~50003), the http option (51236) in this
// package, or the onexmesh.errno.v1 options (51234/51235).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pkg/proto/onexmesh/v1/onexmesh.proto

package onexmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeshService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enable_service_discovery is the master switch: when false or unset, no
	// mesh client code is generated and existing output is unaffected.
	EnableServiceDiscovery bool `protobuf:"varint,1,opt,name=enable_service_discovery,json=enableServiceDiscovery,proto3" json:"enable_service_discovery,omitempty"`
	// service_name is the logical service name in the registry, in the form
	// "{business}.{subdomain-app}.{microservice}", e.g. "edu.course.student-api".
	// When empty, it is inferred from the proto package.
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// registry is the registry backend type: "polaris" (default), "etcd",
	// "kubernetes", "consul", "nacos" or "eureka".
	Registry string `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	// protocol is the transport protocol: "grpc" (default) or "http".
	Protocol      string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshService) Reset() {
	*x = MeshService{}
	mi := &file_pkg_proto_onexmesh_v1_onexmesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshService) ProtoMessage() {}

func (x *MeshService) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_v1_onexmesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshService.ProtoReflect.Descriptor instead.
func (*MeshService) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDescGZIP(), []int{0}
}

func (x *MeshService) GetEnableServiceDiscovery() bool {
	if x != nil {
		return x.EnableServiceDiscovery
	}
	return false
}

func (x *MeshService) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MeshService) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *MeshService) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

var file_pkg_proto_onexmesh_v1_onexmesh_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*MeshService)(nil),
		Field:         50010,
		Name:          "onexmesh.v1.mesh_service",
		Tag:           "bytes,50010,opt,name=mesh_service",
		Filename:      "pkg/proto/onexmesh/v1/onexmesh.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional onexmesh.v1.MeshService mesh_service = 50010;
	E_MeshService = &file_pkg_proto_onexmesh_v1_onexmesh_proto_extTypes[0]
)

var File_pkg_proto_onexmesh_v1_onexmesh_proto protoreflect.FileDescriptor

const file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDesc = "" +
	"\n" +
	"$pkg/proto/onexmesh/v1/onexmesh.proto\x12\vonexmesh.v1\x1a google/protobuf/descriptor.proto\"\xa2\x01\n" +
	"\vMeshService\x128\n" +
	"\x18enable_service_discovery\x18\x01 \x01(\bR\x16enableServiceDiscovery\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bregistry\x18\x03 \x01(\tR\bregistry\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol:[\n" +
	"\fmesh_service\x12\x1c.google.protobuf.FileOptions\x18چ\x03 \x01(\v2\x18.onexmesh.v1.MeshServiceR\vmeshServiceB@Z>github.com/onexstack/onexmesh/pkg/proto/onexmesh/v1;onexmeshv1b\x06proto3"

var (
	file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDescOnce sync.Once
	file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDescData []byte
)

func file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDescGZIP() []byte {
	file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDescOnce.Do(func() {
		file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDesc), len(file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDesc)))
	})
	return file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDescData
}

var file_pkg_proto_onexmesh_v1_onexmesh_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_onexmesh_v1_onexmesh_proto_goTypes = []any{
	(*MeshService)(nil),              // 0: onexmesh.v1.MeshService
	(*descriptorpb.FileOptions)(nil), // 1: google.protobuf.FileOptions
}
var file_pkg_proto_onexmesh_v1_onexmesh_proto_depIdxs = []int32{
	1, // 0: onexmesh.v1.mesh_service:extendee -> google.protobuf.FileOptions
	0, // 1: onexmesh.v1.mesh_service:type_name -> onexmesh.v1.MeshService
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_onexmesh_v1_onexmesh_proto_init() }
func file_pkg_proto_onexmesh_v1_onexmesh_proto_init() {
	if File_pkg_proto_onexmesh_v1_onexmesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDesc), len(file_pkg_proto_onexmesh_v1_onexmesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_onexmesh_v1_onexmesh_proto_goTypes,
		DependencyIndexes: file_pkg_proto_onexmesh_v1_onexmesh_proto_depIdxs,
		MessageInfos:      file_pkg_proto_onexmesh_v1_onexmesh_proto_msgTypes,
		ExtensionInfos:    file_pkg_proto_onexmesh_v1_onexmesh_proto_extTypes,
	}.Build()
	File_pkg_proto_onexmesh_v1_onexmesh_proto = out.File
	file_pkg_proto_onexmesh_v1_onexmesh_proto_goTypes = nil
	file_pkg_proto_onexmesh_v1_onexmesh_proto_depIdxs = nil
}
