// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// The onexmesh.rest.v1 extensions declare the REST semantics of a resource
// message so the protoc-gen-onexmesh-client plugin can generate a client-go
// style SDK (clientset + typed + fake + informer + lister + applyconfigurations).
//
// Extension field numbers live in the reserved custom-option range (>= 50000),
// and are distinct from onexmesh.v1.http (51236), onexmesh.errno.v1
// (51234/51235) and google.api.http (72295728).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pkg/proto/onexmesh/rest/v1/rest.proto

package restv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short API group name, e.g. "apps". Empty means the core group ("").
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// API version, e.g. "v1".
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRest) Reset() {
	*x = FileRest{}
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRest) ProtoMessage() {}

func (x *FileRest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRest.ProtoReflect.Descriptor instead.
func (*FileRest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescGZIP(), []int{0}
}

func (x *FileRest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FileRest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Clientset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package name of the generated clientset, e.g. "exampleclient".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// API path served by the resource groups, "/apis" (or "/api" for the core
	// group).
	ApiPath string `protobuf:"bytes,2,opt,name=api_path,json=apiPath,proto3" json:"api_path,omitempty"`
	// Prefer protobuf encoding over JSON when talking to the server.
	PreferProtobuf bool `protobuf:"varint,3,opt,name=prefer_protobuf,json=preferProtobuf,proto3" json:"prefer_protobuf,omitempty"`
	// The (group, version) pairs aggregated into this clientset.
	Groups        []*GroupRef `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clientset) Reset() {
	*x = Clientset{}
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clientset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clientset) ProtoMessage() {}

func (x *Clientset) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clientset.ProtoReflect.Descriptor instead.
func (*Clientset) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescGZIP(), []int{1}
}

func (x *Clientset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Clientset) GetApiPath() string {
	if x != nil {
		return x.ApiPath
	}
	return ""
}

func (x *Clientset) GetPreferProtobuf() bool {
	if x != nil {
		return x.PreferProtobuf
	}
	return false
}

func (x *Clientset) GetGroups() []*GroupRef {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRef) Reset() {
	*x = GroupRef{}
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRef) ProtoMessage() {}

func (x *GroupRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRef.ProtoReflect.Descriptor instead.
func (*GroupRef) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescGZIP(), []int{2}
}

func (x *GroupRef) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short API group name; empty means core. Defaults to the file-level value.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// API version. Defaults to the file-level value.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// REST plural name, e.g. "deployments". Defaults to lowercase(singular)+"s".
	Plural string `protobuf:"bytes,3,opt,name=plural,proto3" json:"plural,omitempty"`
	// REST singular name, e.g. "deployment". Defaults to lowercase(kind).
	Singular string `protobuf:"bytes,4,opt,name=singular,proto3" json:"singular,omitempty"`
	// Whether the resource is namespace-scoped. Defaults to true. Use
	// "optional bool" so an explicit false (cluster-scoped) is distinguishable
	// from unset.
	Namespaced *bool `protobuf:"varint,5,opt,name=namespaced,proto3,oneof" json:"namespaced,omitempty"`
	// Verb set to generate. Defaults to
	// get,list,watch,create,update,patch,delete (plus updateStatus when the
	// message has a status field).
	Verbs []string `protobuf:"bytes,6,rep,name=verbs,proto3" json:"verbs,omitempty"`
	// Subresources such as status or scale.
	Subresources []*Subresource `protobuf:"bytes,7,rep,name=subresources,proto3" json:"subresources,omitempty"`
	// Group Go name override (aligned with client-gen's +groupGoName).
	ShortGroup string `protobuf:"bytes,8,opt,name=short_group,json=shortGroup,proto3" json:"short_group,omitempty"`
	// Do not generate UpdateStatus/ApplyStatus even if a status field exists.
	NoStatus      bool `protobuf:"varint,9,opt,name=no_status,json=noStatus,proto3" json:"no_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescGZIP(), []int{3}
}

func (x *Resource) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Resource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Resource) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

func (x *Resource) GetSingular() string {
	if x != nil {
		return x.Singular
	}
	return ""
}

func (x *Resource) GetNamespaced() bool {
	if x != nil && x.Namespaced != nil {
		return *x.Namespaced
	}
	return false
}

func (x *Resource) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

func (x *Resource) GetSubresources() []*Subresource {
	if x != nil {
		return x.Subresources
	}
	return nil
}

func (x *Resource) GetShortGroup() string {
	if x != nil {
		return x.ShortGroup
	}
	return ""
}

func (x *Resource) GetNoStatus() bool {
	if x != nil {
		return x.NoStatus
	}
	return false
}

type Subresource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subresource name, e.g. "status".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL path segment; defaults to name.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Verbs to generate for this subresource; defaults to get,update.
	Verbs []string `protobuf:"bytes,3,rep,name=verbs,proto3" json:"verbs,omitempty"`
	// Result kind for this subresource, if different from the parent resource.
	Kind          string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subresource) Reset() {
	*x = Subresource{}
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subresource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subresource) ProtoMessage() {}

func (x *Subresource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subresource.ProtoReflect.Descriptor instead.
func (*Subresource) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescGZIP(), []int{4}
}

func (x *Subresource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subresource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Subresource) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

func (x *Subresource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type List struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent resource of this list type. group/version must match the item.
	Resource      *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *List) Reset() {
	*x = List{}
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescGZIP(), []int{5}
}

func (x *List) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var file_pkg_proto_onexmesh_rest_v1_rest_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileRest)(nil),
		Field:         50000,
		Name:          "onexmesh.rest.v1.file",
		Tag:           "bytes,50000,opt,name=file",
		Filename:      "pkg/proto/onexmesh/rest/v1/rest.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Clientset)(nil),
		Field:         50003,
		Name:          "onexmesh.rest.v1.clientset",
		Tag:           "bytes,50003,opt,name=clientset",
		Filename:      "pkg/proto/onexmesh/rest/v1/rest.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Resource)(nil),
		Field:         50001,
		Name:          "onexmesh.rest.v1.resource",
		Tag:           "bytes,50001,opt,name=resource",
		Filename:      "pkg/proto/onexmesh/rest/v1/rest.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*List)(nil),
		Field:         50002,
		Name:          "onexmesh.rest.v1.list",
		Tag:           "bytes,50002,opt,name=list",
		Filename:      "pkg/proto/onexmesh/rest/v1/rest.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional onexmesh.rest.v1.FileRest file = 50000;
	E_File = &file_pkg_proto_onexmesh_rest_v1_rest_proto_extTypes[0]
	// optional onexmesh.rest.v1.Clientset clientset = 50003;
	E_Clientset = &file_pkg_proto_onexmesh_rest_v1_rest_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional onexmesh.rest.v1.Resource resource = 50001;
	E_Resource = &file_pkg_proto_onexmesh_rest_v1_rest_proto_extTypes[2]
	// optional onexmesh.rest.v1.List list = 50002;
	E_List = &file_pkg_proto_onexmesh_rest_v1_rest_proto_extTypes[3]
)

var File_pkg_proto_onexmesh_rest_v1_rest_proto protoreflect.FileDescriptor

const file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDesc = "" +
	"\n" +
	"%pkg/proto/onexmesh/rest/v1/rest.proto\x12\x10onexmesh.rest.v1\x1a google/protobuf/descriptor.proto\":\n" +
	"\bFileRest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x97\x01\n" +
	"\tClientset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bapi_path\x18\x02 \x01(\tR\aapiPath\x12'\n" +
	"\x0fprefer_protobuf\x18\x03 \x01(\bR\x0epreferProtobuf\x122\n" +
	"\x06groups\x18\x04 \x03(\v2\x1a.onexmesh.rest.v1.GroupRefR\x06groups\":\n" +
	"\bGroupRef\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xb9\x02\n" +
	"\bResource\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06plural\x18\x03 \x01(\tR\x06plural\x12\x1a\n" +
	"\bsingular\x18\x04 \x01(\tR\bsingular\x12#\n" +
	"\n" +
	"namespaced\x18\x05 \x01(\bH\x00R\n" +
	"namespaced\x88\x01\x01\x12\x14\n" +
	"\x05verbs\x18\x06 \x03(\tR\x05verbs\x12A\n" +
	"\fsubresources\x18\a \x03(\v2\x1d.onexmesh.rest.v1.SubresourceR\fsubresources\x12\x1f\n" +
	"\vshort_group\x18\b \x01(\tR\n" +
	"shortGroup\x12\x1b\n" +
	"\tno_status\x18\t \x01(\bR\bnoStatusB\r\n" +
	"\v_namespaced\"_\n" +
	"\vSubresource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05verbs\x18\x03 \x03(\tR\x05verbs\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\">\n" +
	"\x04List\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.onexmesh.rest.v1.ResourceR\bresource:N\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18І\x03 \x01(\v2\x1a.onexmesh.rest.v1.FileRestR\x04file:Y\n" +
	"\tclientset\x12\x1c.google.protobuf.FileOptions\x18ӆ\x03 \x01(\v2\x1b.onexmesh.rest.v1.ClientsetR\tclientset:Y\n" +
	"\bresource\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2\x1a.onexmesh.rest.v1.ResourceR\bresource:M\n" +
	"\x04list\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\v2\x16.onexmesh.rest.v1.ListR\x04listBAZ?github.com/onexstack/onexmesh/pkg/proto/onexmesh/rest/v1;restv1b\x06proto3"

var (
	file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescOnce sync.Once
	file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescData []byte
)

func file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescGZIP() []byte {
	file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescOnce.Do(func() {
		file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDesc), len(file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDesc)))
	})
	return file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDescData
}

var file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_onexmesh_rest_v1_rest_proto_goTypes = []any{
	(*FileRest)(nil),                    // 0: onexmesh.rest.v1.FileRest
	(*Clientset)(nil),                   // 1: onexmesh.rest.v1.Clientset
	(*GroupRef)(nil),                    // 2: onexmesh.rest.v1.GroupRef
	(*Resource)(nil),                    // 3: onexmesh.rest.v1.Resource
	(*Subresource)(nil),                 // 4: onexmesh.rest.v1.Subresource
	(*List)(nil),                        // 5: onexmesh.rest.v1.List
	(*descriptorpb.FileOptions)(nil),    // 6: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 7: google.protobuf.MessageOptions
}
var file_pkg_proto_onexmesh_rest_v1_rest_proto_depIdxs = []int32{
	2,  // 0: onexmesh.rest.v1.Clientset.groups:type_name -> onexmesh.rest.v1.GroupRef
	4,  // 1: onexmesh.rest.v1.Resource.subresources:type_name -> onexmesh.rest.v1.Subresource
	3,  // 2: onexmesh.rest.v1.List.resource:type_name -> onexmesh.rest.v1.Resource
	6,  // 3: onexmesh.rest.v1.file:extendee -> google.protobuf.FileOptions
	6,  // 4: onexmesh.rest.v1.clientset:extendee -> google.protobuf.FileOptions
	7,  // 5: onexmesh.rest.v1.resource:extendee -> google.protobuf.MessageOptions
	7,  // 6: onexmesh.rest.v1.list:extendee -> google.protobuf.MessageOptions
	0,  // 7: onexmesh.rest.v1.file:type_name -> onexmesh.rest.v1.FileRest
	1,  // 8: onexmesh.rest.v1.clientset:type_name -> onexmesh.rest.v1.Clientset
	3,  // 9: onexmesh.rest.v1.resource:type_name -> onexmesh.rest.v1.Resource
	5,  // 10: onexmesh.rest.v1.list:type_name -> onexmesh.rest.v1.List
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	7,  // [7:11] is the sub-list for extension type_name
	3,  // [3:7] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_onexmesh_rest_v1_rest_proto_init() }
func file_pkg_proto_onexmesh_rest_v1_rest_proto_init() {
	if File_pkg_proto_onexmesh_rest_v1_rest_proto != nil {
		return
	}
	file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDesc), len(file_pkg_proto_onexmesh_rest_v1_rest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_onexmesh_rest_v1_rest_proto_goTypes,
		DependencyIndexes: file_pkg_proto_onexmesh_rest_v1_rest_proto_depIdxs,
		MessageInfos:      file_pkg_proto_onexmesh_rest_v1_rest_proto_msgTypes,
		ExtensionInfos:    file_pkg_proto_onexmesh_rest_v1_rest_proto_extTypes,
	}.Build()
	File_pkg_proto_onexmesh_rest_v1_rest_proto = out.File
	file_pkg_proto_onexmesh_rest_v1_rest_proto_goTypes = nil
	file_pkg_proto_onexmesh_rest_v1_rest_proto_depIdxs = nil
}
