// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// protoc-gen-onexmesh-client is a plugin for the protocol buffer compiler that
// generates a client-go style REST SDK (clientset + typed clients + scheme +
// fake + informers + listers + applyconfigurations) from protobuf IDL, plus a
// mesh-aware gRPC client for services flagged with onexmesh.v1.mesh_service.
// The gRPC SDK itself is generated by the standard protoc-gen-go-grpc plugin.
//
// Install it by building this program and placing it on your PATH as
// protoc-gen-onexmesh-client. The "onexmesh-client" suffix becomes part of the
// protoc argument:
//
//	protoc --onexmesh-client_out=. path/to/file.proto
package main

import (
	"flag"
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators/applycfg"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators/fake"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators/informer"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators/lister"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators/mesh"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators/meta"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators/register"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators/scheme"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/generators/typed"
	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/spec"
)

const version = "0.1.0"

func main() {
	showVersion := flag.Bool("version", false, "print the version and exit")
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-onexmesh-client %v\n", version)
		return
	}

	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL) |
			uint64(pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS)

		s, err := spec.Load(gen)
		if err != nil {
			return err
		}

		generateClientsetFiles(gen, s)
		generateFakeClientset(gen, s)
		generateInformerFiles(gen, s)
		generateMeshFiles(gen, s)
		for _, group := range s.Groups {
			for _, vs := range group.Versions {
				generateVersionFiles(gen, vs)
				generateApplyConfigFiles(gen, s, group, vs)
				generateTypedFiles(gen, s, group, vs)
				generateListerFiles(gen, s, group, vs)
			}
		}
		return nil
	})
}

// generateFakeClientset generates the top-level fake clientset.
func generateFakeClientset(gen *protogen.Plugin, s *spec.Spec) {
	write(gen, path.Join(s.ClientsetProtoDir, "fake", "clientset.go"), s.ClientsetGoPackage+"/fake", fake.GenerateClientset(s))
}

// generateMeshFiles generates the onexmesh service-discovery clients for gRPC
// services flagged with onexmesh.v1.mesh_service.
func generateMeshFiles(gen *protogen.Plugin, s *spec.Spec) {
	for _, fm := range s.Meshes {
		write(gen, path.Join(fm.ProtoDir, "zz_generated.mesh.go"), fm.GoImportPath, mesh.Generate(fm))
		if len(fm.Methods) > 0 {
			write(gen, path.Join(fm.ProtoDir, "zz_generated.httpclient.go"), fm.GoImportPath, mesh.GenerateHTTPClient(fm))
		}
	}
}

// generateClientsetFiles generates the top-level clientset.go and scheme
// package under the anchor clientset directory.
func generateClientsetFiles(gen *protogen.Plugin, s *spec.Spec) {
	write(gen, path.Join(s.ClientsetProtoDir, "clientset.go"), s.ClientsetGoPackage, typed.GenerateClientset(s))
	write(gen, path.Join(s.ClientsetProtoDir, "scheme", "register.go"), s.ClientsetGoPackage+"/scheme", scheme.Generate(s))
	write(gen, path.Join(s.ClientsetProtoDir, "scheme", "doc.go"), s.ClientsetGoPackage+"/scheme", "// Package scheme contains the scheme for this clientset.\npackage scheme\n")
}

// generateVersionFiles generates the per-group/version files that land in the
// API types package: the meta adapter and the scheme registration.
func generateVersionFiles(gen *protogen.Plugin, vs *spec.VersionSpec) {
	write(gen, path.Join(vs.ProtoDir, "zz_generated.meta.go"), vs.GoPackage, meta.Generate(vs))
	write(gen, path.Join(vs.ProtoDir, "zz_generated.register.go"), vs.GoPackage, register.Generate(vs))
}

// generateApplyConfigFiles generates the per-group/version apply configuration
// types into a dedicated applyconfigurations/<group>/<version> package.
func generateApplyConfigFiles(gen *protogen.Plugin, s *spec.Spec, group *spec.GroupSpec, vs *spec.VersionSpec) {
	dir := path.Join(s.ClientsetProtoDir, "applyconfigurations", groupPkgName(group), vs.Version)
	importPath := s.ClientsetGoPackage + "/applyconfigurations/" + groupPkgName(group) + "/" + vs.Version
	write(gen, path.Join(dir, "zz_generated.applyconfiguration.go"), importPath, applycfg.Generate(s, group, vs))
}

// generateTypedFiles generates the typed clients for a group/version.
func generateTypedFiles(gen *protogen.Plugin, s *spec.Spec, group *spec.GroupSpec, vs *spec.VersionSpec) {
	tc := typed.NewTypeContext(s, group, vs)
	dir := path.Join(s.ClientsetProtoDir, "typed", groupPkgName(group), vs.Version)
	importPath := s.ClientsetGoPackage + "/typed/" + groupPkgName(group) + "/" + vs.Version

	write(gen, path.Join(dir, groupPkgName(group)+"_client.go"), importPath, typed.GenerateGroup(tc))
	write(gen, path.Join(dir, "generated_expansion.go"), importPath, typed.GenerateExpansion(tc))
	for _, rs := range vs.Resources {
		write(gen, path.Join(dir, lowerKind(rs.Kind)+".go"), importPath, typed.GenerateType(tc, rs))
	}

	// Fake typed clients.
	fakeDir := path.Join(dir, "fake")
	fakeImportPath := importPath + "/fake"
	write(gen, path.Join(fakeDir, "fake_"+groupPkgName(group)+"_client.go"), fakeImportPath, fake.GenerateGroup(tc))
	for _, rs := range vs.Resources {
		write(gen, path.Join(fakeDir, "fake_"+lowerKind(rs.Kind)+".go"), fakeImportPath, fake.GenerateType(tc, rs))
	}
}

func groupPkgName(g *spec.GroupSpec) string {
	if g.Group == "" {
		return "core"
	}
	return g.Group
}

// lowerKind returns the lowercase kind used for generated file names, e.g.
// "DaemonSet" -> "daemonset" (full lowercase, matching client-go conventions).
func lowerKind(kind string) string {
	return strings.ToLower(kind)
}

// generateInformerFiles generates the informers/ subtree (factory, generic,
// internalinterfaces, group/version interfaces, per-resource informers).
func generateInformerFiles(gen *protogen.Plugin, s *spec.Spec) {
	root := s.ClientsetGoPackage + "/informers"
	dir := path.Join(s.ClientsetProtoDir, "informers")

	write(gen, path.Join(dir, "factory.go"), root, informer.GenerateFactory(s))
	write(gen, path.Join(dir, "generic.go"), root, informer.GenerateGeneric(s))
	write(gen, path.Join(dir, "internalinterfaces", "factory_interfaces.go"), root+"/internalinterfaces", informer.GenerateInternalInterfaces(s))

	for _, group := range s.Groups {
		groupDir := path.Join(dir, groupPkgName(group))
		groupPath := root + "/" + groupPkgName(group)
		write(gen, path.Join(groupDir, "interface.go"), groupPath, informer.GenerateGroupInterface(s, group))

		for _, vs := range group.Versions {
			versionDir := path.Join(groupDir, vs.Version)
			versionPath := groupPath + "/" + vs.Version
			write(gen, path.Join(versionDir, "interface.go"), versionPath, informer.GenerateVersionInterface(s, group, vs))
			for _, rs := range vs.Resources {
				write(gen, path.Join(versionDir, lowerKind(rs.Kind)+".go"), versionPath, informer.GenerateInformer(s, group, vs, rs))
			}
		}
	}
}

// generateListerFiles generates the listers/<group>/<version> files.
func generateListerFiles(gen *protogen.Plugin, s *spec.Spec, group *spec.GroupSpec, vs *spec.VersionSpec) {
	dir := path.Join(s.ClientsetProtoDir, "listers", groupPkgName(group), vs.Version)
	importPath := s.ClientsetGoPackage + "/listers/" + groupPkgName(group) + "/" + vs.Version

	write(gen, path.Join(dir, "expansion_generated.go"), importPath, lister.GenerateExpansion(vs))
	for _, rs := range vs.Resources {
		write(gen, path.Join(dir, lowerKind(rs.Kind)+".go"), importPath, lister.GenerateLister(s, group, vs, rs))
	}
}

func write(gen *protogen.Plugin, filename, importPath, content string) {
	formatted, err := generators.FormatSource(filename, content)
	if err != nil {
		// Surface a parse error with context rather than emitting broken code.
		panic(err)
	}
	g := gen.NewGeneratedFile(filename, protogen.GoImportPath(importPath))
	g.Write([]byte(formatted))
}
