// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

package mesh

import (
	"strings"
	"testing"

	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/spec"
)

func TestGenerate(t *testing.T) {
	fm := &spec.FileMesh{
		GoImportPath: "github.com/onexstack/onexmesh/examples/apis/apps/v1",
		PackageName:  "v1",
		ServiceName:  "DeploymentService",
		ClientName:   "DeploymentServiceClient",
		NewClientFn:  "NewDeploymentServiceClient",
		ProtoDir:     "examples/apis/apps/v1",
		Mesh: spec.MeshSpec{
			ServiceName: "edu.course.student-api",
			Registry:    "polaris",
		},
	}

	out := Generate(fm)

	for _, want := range []string{
		"package v1",
		`const DeploymentServiceName = "edu.course.student-api"`,
		"func NewDeploymentServiceMeshClient(ctx context.Context, opts ...meshclient.DialOption) (DeploymentServiceClient, error)",
		"meshclient.Dial(ctx, DeploymentServiceName, opts...)",
		"NewDeploymentServiceClient(conn)",
		`meshclient "github.com/onexstack/onexmesh/pkg/client"`,
		"Code generated by protoc-gen-onexmesh-client",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("Generate output missing %q\n---\n%s", want, out)
		}
	}
}

func TestGenerateHTTPClient(t *testing.T) {
	fm := &spec.FileMesh{
		PackageName: "appsv1",
		ServiceName: "DeploymentService",
		Mesh:        spec.MeshSpec{ServiceName: "edu.course.student-api"},
		Methods: []*spec.HTTPMethodSpec{
			{Name: "Get", Method: "GET", Path: "/deployments/{name}", Body: "", RequestType: "GetRequest", ResponseType: "GetReply"},
		},
	}

	out := GenerateHTTPClient(fm)

	for _, want := range []string{
		"package appsv1",
		"type DeploymentServiceHTTPClient struct",
		"func NewDeploymentServiceHTTPClient(ctx context.Context, opts ...meshclient.HTTPOption) (*DeploymentServiceHTTPClient, error)",
		"func (c *DeploymentServiceHTTPClient) Get(ctx context.Context, req *GetRequest) (*GetReply, error)",
		`codec.BuildPath("/deployments/{name}", req)`,
		`c.c.Do(ctx, "GET", path, nil, resp)`,
		"Code generated by protoc-gen-onexmesh-client",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("GenerateHTTPClient output missing %q\n---\n%s", want, out)
		}
	}
}
