// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

package mesh

import (
	"strings"
	"testing"

	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/spec"
)

func TestGenerate(t *testing.T) {
	fm := &spec.FileMesh{
		GoImportPath: "github.com/onexstack/onexmesh/examples/apis/apps/v1",
		PackageName:  "v1",
		ServiceName:  "DeploymentService",
		ClientName:   "DeploymentServiceClient",
		NewClientFn:  "NewDeploymentServiceClient",
		ProtoDir:     "examples/apis/apps/v1",
		Mesh: spec.MeshSpec{
			Enabled:     true,
			ServiceName: "edu.course.student-api",
			Registry:    "polaris",
			Protocol:    "grpc",
		},
	}

	out := Generate(fm)

	for _, want := range []string{
		"package v1",
		`const DeploymentServiceName = "edu.course.student-api"`,
		"func NewDeploymentServiceMeshClient(ctx context.Context, opts ...meshclient.DialOption) (DeploymentServiceClient, error)",
		`meshclient.WithRegistry("polaris", &polaris.Options{})`,
		"meshclient.Dial(ctx, DeploymentServiceName, opts...)",
		"NewDeploymentServiceClient(conn)",
		`polaris "github.com/onexstack/onexmesh/pkg/registry/polaris"`,
		"Code generated by protoc-gen-onexmesh-client",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("Generate output missing %q\n---\n%s", want, out)
		}
	}
}
