// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Package mesh renders the onexmesh service-discovery client for a gRPC
// service, generated only when the file declares onexmesh.v1.mesh_service with
// enable_service_discovery=true.
package mesh

import (
	"fmt"
	"strings"

	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/spec"
)

// Generate renders zz_generated.mesh.go for a single gRPC service.
func Generate(fm *spec.FileMesh) string {
	var b strings.Builder
	b.WriteString("// Code generated by protoc-gen-onexmesh-client. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", fm.PackageName)
	b.WriteString(imports(fm))

	fmt.Fprintf(&b, "// %sName is the logical service name in the registry.\n", fm.ServiceName)
	fmt.Fprintf(&b, "const %sName = %q\n\n", fm.ServiceName, fm.Mesh.ServiceName)

	fmt.Fprintf(&b, "// New%sMeshClient discovers %q and returns a typed gRPC client.\n", fm.ServiceName, fm.Mesh.ServiceName)
	fmt.Fprintf(&b, "func New%sMeshClient(ctx context.Context, opts ...meshclient.DialOption) (%s, error) {\n", fm.ServiceName, fm.ClientName)
	b.WriteString("\topts = append([]meshclient.DialOption{\n")
	fmt.Fprintf(&b, "\t\tmeshclient.WithRegistry(%q, &%s.Options{}),\n", fm.Mesh.Registry, registryPkg(fm.Mesh.Registry))
	b.WriteString("\t}, opts...)\n\n")
	fmt.Fprintf(&b, "\tconn, err := meshclient.Dial(ctx, %sName, opts...)\n", fm.ServiceName)
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	fmt.Fprintf(&b, "\treturn %s(conn), nil\n", fm.NewClientFn)
	b.WriteString("}\n")
	return b.String()
}

func imports(fm *spec.FileMesh) string {
	var b strings.Builder
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n\n")
	b.WriteString("\tmeshclient \"github.com/onexstack/onexmesh/pkg/client\"\n")
	fmt.Fprintf(&b, "\t%s \"github.com/onexstack/onexmesh/pkg/registry/%s\"\n", registryPkg(fm.Mesh.Registry), fm.Mesh.Registry)
	b.WriteString(")\n\n")
	return b.String()
}

// registryPkg maps a registry backend name to its Go package alias.
func registryPkg(registry string) string {
	switch registry {
	case "etcd":
		return "etcd"
	case "kubernetes":
		return "kubernetes"
	case "consul":
		return "consul"
	case "nacos":
		return "nacos"
	case "eureka":
		return "eureka"
	default:
		return "polaris"
	}
}
