// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Package register generates zz_generated.register.go, which registers the
// resource types of a group/version into a runtime.Scheme (mirroring the
// output of k8s.io/code-generator's register-gen).
package register

import (
	"fmt"
	"strings"

	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/spec"
)

// Generate renders the full zz_generated.register.go for a group/version.
func Generate(vs *spec.VersionSpec) string {
	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "package %s\n\n", vs.GoPackageName)
	b.WriteString(imports)
	fmt.Fprintf(&b, "// SchemeGroupVersion is the group/version used to register these types.\n")
	fmt.Fprintf(&b, "var SchemeGroupVersion = schema.GroupVersion{Group: %q, Version: %q}\n\n", vs.Group, vs.Version)
	fmt.Fprintf(&b, "// Resource takes an unqualified resource name and returns a GroupResource.\n")
	b.WriteString("func Resource(resource string) schema.GroupResource {\n")
	b.WriteString("\treturn SchemeGroupVersion.WithResource(resource).GroupResource()\n")
	b.WriteString("}\n\n")
	b.WriteString("var (\n")
	b.WriteString("\tSchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)\n")
	b.WriteString("\tAddToScheme   = SchemeBuilder.AddToScheme\n")
	b.WriteString(")\n\n")
	b.WriteString("// addKnownTypes adds the list of known types to the given scheme.\n")
	b.WriteString("func addKnownTypes(scheme *runtime.Scheme) error {\n")
	b.WriteString("\tscheme.AddKnownTypes(SchemeGroupVersion,\n")
	for _, rs := range vs.Resources {
		fmt.Fprintf(&b, "\t\t&%s{},\n", rs.Kind)
		if rs.ListKind != "" {
			fmt.Fprintf(&b, "\t\t&%s{},\n", rs.ListKind)
		}
	}
	b.WriteString("\t)\n")
	b.WriteString("\tmetav1.AddToGroupVersion(scheme, SchemeGroupVersion)\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")

	return b.String()
}

const header = `// Code generated by protoc-gen-onexmesh-client. DO NOT EDIT.

`

const imports = `import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

`
