// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Deployment demonstrates a resource-style REST object. The message-level
// onexmesh.rest.v1.resource option marks it as a REST resource, and the
// file-level onexmesh.rest.v1.file option supplies the default group/version.
//
// NOTE: the conventional top-level fields (apiVersion/kind/metadata) use the
// camelCase convention so the generated Go json tags match the Kubernetes JSON
// wire format, mirroring the onexmesh.meta.v1 types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: examples/apis/apps/v1/deployment.proto

package appsv1

import (
	v1 "github.com/onexstack/onexmesh/pkg/proto/onexmesh/meta/v1"
	_ "github.com/onexstack/onexmesh/pkg/proto/onexmesh/rest/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      int32                  `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentSpec) Reset() {
	*x = DeploymentSpec{}
	mi := &file_examples_apis_apps_v1_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentSpec) ProtoMessage() {}

func (x *DeploymentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_examples_apis_apps_v1_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentSpec.ProtoReflect.Descriptor instead.
func (*DeploymentSpec) Descriptor() ([]byte, []int) {
	return file_examples_apis_apps_v1_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *DeploymentSpec) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *DeploymentSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *v1.ObjectMeta         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *DeploymentSpec        `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_examples_apis_apps_v1_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_examples_apis_apps_v1_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_examples_apis_apps_v1_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *Deployment) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Deployment) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Deployment) GetMetadata() *v1.ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Deployment) GetSpec() *DeploymentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Deployment) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeploymentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *v1.ListMeta           `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items         []*Deployment          `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentList) Reset() {
	*x = DeploymentList{}
	mi := &file_examples_apis_apps_v1_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentList) ProtoMessage() {}

func (x *DeploymentList) ProtoReflect() protoreflect.Message {
	mi := &file_examples_apis_apps_v1_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentList.ProtoReflect.Descriptor instead.
func (*DeploymentList) Descriptor() ([]byte, []int) {
	return file_examples_apis_apps_v1_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *DeploymentList) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *DeploymentList) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DeploymentList) GetMetadata() *v1.ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DeploymentList) GetItems() []*Deployment {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_examples_apis_apps_v1_deployment_proto protoreflect.FileDescriptor

const file_examples_apis_apps_v1_deployment_proto_rawDesc = "" +
	"\n" +
	"&examples/apis/apps/v1/deployment.proto\x12\x10examples.apps.v1\x1a\x1bonexmesh/meta/v1/meta.proto\x1a\x1bonexmesh/rest/v1/rest.proto\"B\n" +
	"\x0eDeploymentSpec\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"\xce\x01\n" +
	"\n" +
	"Deployment\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x128\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1c.onexmesh.meta.v1.ObjectMetaR\bmetadata\x124\n" +
	"\x04spec\x18\x04 \x01(\v2 .examples.apps.v1.DeploymentSpecR\x04spec\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status:\x04\x8a\xb5\x18\x00\"\xb6\x01\n" +
	"\x0eDeploymentList\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x126\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1a.onexmesh.meta.v1.ListMetaR\bmetadata\x122\n" +
	"\x05items\x18\x04 \x03(\v2\x1c.examples.apps.v1.DeploymentR\x05items:\x04\x92\xb5\x18\x00BJ\x82\xb5\x18\n" +
	"\n" +
	"\x04apps\x12\x02v1Z:github.com/onexstack/onexmesh/examples/apis/apps/v1;appsv1b\x06proto3"

var (
	file_examples_apis_apps_v1_deployment_proto_rawDescOnce sync.Once
	file_examples_apis_apps_v1_deployment_proto_rawDescData []byte
)

func file_examples_apis_apps_v1_deployment_proto_rawDescGZIP() []byte {
	file_examples_apis_apps_v1_deployment_proto_rawDescOnce.Do(func() {
		file_examples_apis_apps_v1_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_apis_apps_v1_deployment_proto_rawDesc), len(file_examples_apis_apps_v1_deployment_proto_rawDesc)))
	})
	return file_examples_apis_apps_v1_deployment_proto_rawDescData
}

var file_examples_apis_apps_v1_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_apis_apps_v1_deployment_proto_goTypes = []any{
	(*DeploymentSpec)(nil), // 0: examples.apps.v1.DeploymentSpec
	(*Deployment)(nil),     // 1: examples.apps.v1.Deployment
	(*DeploymentList)(nil), // 2: examples.apps.v1.DeploymentList
	(*v1.ObjectMeta)(nil),  // 3: onexmesh.meta.v1.ObjectMeta
	(*v1.ListMeta)(nil),    // 4: onexmesh.meta.v1.ListMeta
}
var file_examples_apis_apps_v1_deployment_proto_depIdxs = []int32{
	3, // 0: examples.apps.v1.Deployment.metadata:type_name -> onexmesh.meta.v1.ObjectMeta
	0, // 1: examples.apps.v1.Deployment.spec:type_name -> examples.apps.v1.DeploymentSpec
	4, // 2: examples.apps.v1.DeploymentList.metadata:type_name -> onexmesh.meta.v1.ListMeta
	1, // 3: examples.apps.v1.DeploymentList.items:type_name -> examples.apps.v1.Deployment
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_examples_apis_apps_v1_deployment_proto_init() }
func file_examples_apis_apps_v1_deployment_proto_init() {
	if File_examples_apis_apps_v1_deployment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_apis_apps_v1_deployment_proto_rawDesc), len(file_examples_apis_apps_v1_deployment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_apis_apps_v1_deployment_proto_goTypes,
		DependencyIndexes: file_examples_apis_apps_v1_deployment_proto_depIdxs,
		MessageInfos:      file_examples_apis_apps_v1_deployment_proto_msgTypes,
	}.Build()
	File_examples_apis_apps_v1_deployment_proto = out.File
	file_examples_apis_apps_v1_deployment_proto_goTypes = nil
	file_examples_apis_apps_v1_deployment_proto_depIdxs = nil
}
