// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// DeploymentService demonstrates a gRPC service flagged for onexmesh
// service-discovery code generation. The file-level onexmesh.v1.mesh_service
// option turns on generation of zz_generated.mesh.go with a
// NewDeploymentServiceMeshClient constructor that discovers the service via the
// registry and dials it through pkg/client.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: examples/apis/apps/v1/service.proto

package appsv1

import (
	_ "github.com/onexstack/onexmesh/pkg/proto/onexmesh/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_examples_apis_apps_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_apis_apps_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_examples_apis_apps_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_examples_apis_apps_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_examples_apis_apps_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_examples_apis_apps_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_examples_apis_apps_v1_service_proto protoreflect.FileDescriptor

const file_examples_apis_apps_v1_service_proto_rawDesc = "" +
	"\n" +
	"#examples/apis/apps/v1/service.proto\x12\x10examples.apps.v1\x1a\x1aonexmesh/v1/onexmesh.proto\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\bGetReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2T\n" +
	"\x11DeploymentService\x12?\n" +
	"\x03Get\x12\x1c.examples.apps.v1.GetRequest\x1a\x1a.examples.apps.v1.GetReplyBfҵ\x18&\b\x01\x12\x16edu.course.student-api\x1a\x04etcd\"\x04grpcZ:github.com/onexstack/onexmesh/examples/apis/apps/v1;appsv1b\x06proto3"

var (
	file_examples_apis_apps_v1_service_proto_rawDescOnce sync.Once
	file_examples_apis_apps_v1_service_proto_rawDescData []byte
)

func file_examples_apis_apps_v1_service_proto_rawDescGZIP() []byte {
	file_examples_apis_apps_v1_service_proto_rawDescOnce.Do(func() {
		file_examples_apis_apps_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_apis_apps_v1_service_proto_rawDesc), len(file_examples_apis_apps_v1_service_proto_rawDesc)))
	})
	return file_examples_apis_apps_v1_service_proto_rawDescData
}

var file_examples_apis_apps_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_apis_apps_v1_service_proto_goTypes = []any{
	(*GetRequest)(nil), // 0: examples.apps.v1.GetRequest
	(*GetReply)(nil),   // 1: examples.apps.v1.GetReply
}
var file_examples_apis_apps_v1_service_proto_depIdxs = []int32{
	0, // 0: examples.apps.v1.DeploymentService.Get:input_type -> examples.apps.v1.GetRequest
	1, // 1: examples.apps.v1.DeploymentService.Get:output_type -> examples.apps.v1.GetReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_apis_apps_v1_service_proto_init() }
func file_examples_apis_apps_v1_service_proto_init() {
	if File_examples_apis_apps_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_apis_apps_v1_service_proto_rawDesc), len(file_examples_apis_apps_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_apis_apps_v1_service_proto_goTypes,
		DependencyIndexes: file_examples_apis_apps_v1_service_proto_depIdxs,
		MessageInfos:      file_examples_apis_apps_v1_service_proto_msgTypes,
	}.Build()
	File_examples_apis_apps_v1_service_proto = out.File
	file_examples_apis_apps_v1_service_proto_goTypes = nil
	file_examples_apis_apps_v1_service_proto_depIdxs = nil
}
