// Code generated by protoc-gen-onexmesh-client. DO NOT EDIT.

package appsv1

import (
	"context"

	meshclient "github.com/onexstack/onexmesh/pkg/client"
	etcd "github.com/onexstack/onexmesh/pkg/registry/etcd"
)

// DeploymentServiceName is the logical service name in the registry.
const DeploymentServiceName = "edu.course.student-api"

// NewDeploymentServiceMeshClient discovers "edu.course.student-api" and returns a typed gRPC client.
func NewDeploymentServiceMeshClient(ctx context.Context, opts ...meshclient.DialOption) (DeploymentServiceClient, error) {
	opts = append([]meshclient.DialOption{
		meshclient.WithRegistry("etcd", &etcd.Options{}),
	}, opts...)

	conn, err := meshclient.Dial(ctx, DeploymentServiceName, opts...)
	if err != nil {
		return nil, err
	}
	return NewDeploymentServiceClient(conn), nil
}
