// Code generated by protoc-gen-onexmesh-client. DO NOT EDIT.

package appsv1

import (
	proto "google.golang.org/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"

	meshmeta "github.com/onexstack/onexmesh/pkg/proto/onexmesh/meta/v1"
)

// Deployment implements runtime.Object and metav1.Object.
var _ runtime.Object = &Deployment{}
var _ metav1.Object = &Deployment{}

func (in *Deployment) GetObjectKind() schema.ObjectKind { return in }

func (in *Deployment) GroupVersionKind() schema.GroupVersionKind {
	return schema.FromAPIVersionAndKind(in.ApiVersion, in.Kind)
}

func (in *Deployment) SetGroupVersionKind(gvk schema.GroupVersionKind) {
	in.ApiVersion, in.Kind = gvk.ToAPIVersionAndKind()
}

func (in *Deployment) DeepCopyObject() runtime.Object {
	return proto.Clone(in).(*Deployment)
}

func (in *Deployment) GetName() string {
	if in.Metadata != nil {
		return in.Metadata.Name
	}
	return ""
}

func (in *Deployment) SetName(name string) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.Name = name
}

func (in *Deployment) GetGenerateName() string {
	if in.Metadata != nil {
		return in.Metadata.GenerateName
	}
	return ""
}

func (in *Deployment) SetGenerateName(generateName string) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.GenerateName = generateName
}

func (in *Deployment) GetNamespace() string {
	if in.Metadata != nil {
		return in.Metadata.Namespace
	}
	return ""
}

func (in *Deployment) SetNamespace(namespace string) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.Namespace = namespace
}

func (in *Deployment) GetSelfLink() string {
	if in.Metadata != nil {
		return in.Metadata.SelfLink
	}
	return ""
}

func (in *Deployment) SetSelfLink(selfLink string) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.SelfLink = selfLink
}

func (in *Deployment) GetResourceVersion() string {
	if in.Metadata != nil {
		return in.Metadata.ResourceVersion
	}
	return ""
}

func (in *Deployment) SetResourceVersion(resourceVersion string) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.ResourceVersion = resourceVersion
}

func (in *Deployment) GetUID() types.UID {
	if in.Metadata != nil {
		return types.UID(in.Metadata.Uid)
	}
	return ""
}

func (in *Deployment) SetUID(uid types.UID) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.Uid = string(uid)
}

func (in *Deployment) GetGeneration() int64 {
	if in.Metadata != nil {
		return in.Metadata.Generation
	}
	return 0
}

func (in *Deployment) SetGeneration(generation int64) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.Generation = generation
}

func (in *Deployment) GetCreationTimestamp() metav1.Time {
	if in.Metadata != nil && in.Metadata.CreationTimestamp != nil {
		return metav1.Time{Time: in.Metadata.CreationTimestamp.AsTime()}
	}
	return metav1.Time{}
}

func (in *Deployment) SetCreationTimestamp(timestamp metav1.Time) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.CreationTimestamp = timestamppb.New(timestamp.Time)
}

func (in *Deployment) GetDeletionTimestamp() *metav1.Time {
	if in.Metadata != nil && in.Metadata.DeletionTimestamp != nil {
		return &metav1.Time{Time: in.Metadata.DeletionTimestamp.AsTime()}
	}
	return nil
}

func (in *Deployment) SetDeletionTimestamp(timestamp *metav1.Time) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	if timestamp != nil {
		in.Metadata.DeletionTimestamp = timestamppb.New(timestamp.Time)
	} else {
		in.Metadata.DeletionTimestamp = nil
	}
}

func (in *Deployment) GetDeletionGracePeriodSeconds() *int64 {
	if in.Metadata != nil {
		return in.Metadata.DeletionGracePeriodSeconds
	}
	return nil
}

func (in *Deployment) SetDeletionGracePeriodSeconds(seconds *int64) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.DeletionGracePeriodSeconds = seconds
}

func (in *Deployment) GetLabels() map[string]string {
	if in.Metadata != nil {
		return in.Metadata.Labels
	}
	return nil
}

func (in *Deployment) SetLabels(labels map[string]string) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.Labels = labels
}

func (in *Deployment) GetAnnotations() map[string]string {
	if in.Metadata != nil {
		return in.Metadata.Annotations
	}
	return nil
}

func (in *Deployment) SetAnnotations(annotations map[string]string) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.Annotations = annotations
}

func (in *Deployment) GetFinalizers() []string {
	if in.Metadata != nil {
		return in.Metadata.Finalizers
	}
	return nil
}

func (in *Deployment) SetFinalizers(finalizers []string) {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ObjectMeta{}
	}
	in.Metadata.Finalizers = finalizers
}

func (in *Deployment) GetOwnerReferences() []metav1.OwnerReference { return nil }

func (in *Deployment) SetOwnerReferences(references []metav1.OwnerReference) {}

func (in *Deployment) GetManagedFields() []metav1.ManagedFieldsEntry { return nil }

func (in *Deployment) SetManagedFields(managedFields []metav1.ManagedFieldsEntry) {}

// DeploymentList implements runtime.Object and metav1.ListMetaAccessor.
var _ runtime.Object = &DeploymentList{}
var _ metav1.ListMetaAccessor = &DeploymentList{}

func (in *DeploymentList) GetObjectKind() schema.ObjectKind { return in }

func (in *DeploymentList) GroupVersionKind() schema.GroupVersionKind {
	return schema.FromAPIVersionAndKind(in.ApiVersion, in.Kind)
}

func (in *DeploymentList) SetGroupVersionKind(gvk schema.GroupVersionKind) {
	in.ApiVersion, in.Kind = gvk.ToAPIVersionAndKind()
}

func (in *DeploymentList) DeepCopyObject() runtime.Object {
	return proto.Clone(in).(*DeploymentList)
}

func (in *DeploymentList) GetListMeta() metav1.ListInterface {
	if in.Metadata == nil {
		in.Metadata = &meshmeta.ListMeta{}
	}
	return &meshListMetaAdapter{in.Metadata}
}

// meshListMetaAdapter adapts *meshmeta.ListMeta to metav1.ListInterface.
type meshListMetaAdapter struct {
	m *meshmeta.ListMeta
}

func (a *meshListMetaAdapter) GetResourceVersion() string {
	if a.m != nil {
		return a.m.ResourceVersion
	}
	return ""
}

func (a *meshListMetaAdapter) SetResourceVersion(v string) {
	if a.m != nil {
		a.m.ResourceVersion = v
	}
}

func (a *meshListMetaAdapter) GetSelfLink() string { return "" }

func (a *meshListMetaAdapter) SetSelfLink(v string) {}

func (a *meshListMetaAdapter) GetContinue() string {
	if a.m != nil {
		return a.m.Continue
	}
	return ""
}

func (a *meshListMetaAdapter) SetContinue(v string) {
	if a.m != nil {
		a.m.Continue = v
	}
}

func (a *meshListMetaAdapter) GetRemainingItemCount() *int64 {
	if a.m != nil {
		return a.m.RemainingItemCount
	}
	return nil
}

func (a *meshListMetaAdapter) SetRemainingItemCount(v *int64) {
	if a.m != nil {
		a.m.RemainingItemCount = v
	}
}
