// Code generated by protoc-gen-onexmesh-client. DO NOT EDIT.

package appsv1

import (
	"context"

	meshclient "github.com/onexstack/onexmesh/pkg/client"
	"github.com/onexstack/onexmesh/pkg/codec"
)

// DeploymentServiceHTTPClient is a typed HTTP client for the DeploymentService service. It
// discovers the service via the onexmesh registry and encodes/decodes
// protobuf request/response messages with the configured codec (JSON by default).
type DeploymentServiceHTTPClient struct {
	c *meshclient.HTTPClient
}

// NewDeploymentServiceHTTPClient discovers "edu.course.student-api" and returns a
// typed HTTP client. Pass meshclient.WithHTTPRegistry / WithHTTPCodec /
// WithHTTPSelector etc. to configure discovery, codec and load balancing.
func NewDeploymentServiceHTTPClient(ctx context.Context, opts ...meshclient.HTTPOption) (*DeploymentServiceHTTPClient, error) {
	c, err := meshclient.NewHTTPClient(DeploymentServiceName, opts...)
	if err != nil {
		return nil, err
	}
	return &DeploymentServiceHTTPClient{c: c}, nil
}

// Get calls GET /deployments/{name} on the service.
func (c *DeploymentServiceHTTPClient) Get(ctx context.Context, req *GetRequest) (*GetReply, error) {
	path, err := codec.BuildPath("/deployments/{name}", req)
	if err != nil {
		return nil, err
	}
	resp := &GetReply{}
	err = c.c.Do(ctx, "GET", path, nil, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
