// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Command protoc-gen-onexmesh is a protoc plugin that generates HTTP route
// registration code for a service whose methods carry the onexmesh.v1.http
// annotation (see pkg/proto/onexmesh/v1/http.proto).
//
// For an annotated method:
//
//	service Greeter {
//	  rpc SayHello(HelloRequest) returns (HelloReply) {
//	    option (onexmesh.v1.http) = { get: "/helloworld/{name}" };
//	  }
//	}
//
// it emits a *_http.pb.go with:
//
//	func RegisterGreeterHTTPServer(e *gin.Engine, srv GreeterServer)
//	func NewGreeterService(srv GreeterServer) server.Service
//
// where RegisterGreeterHTTPServer registers the gin routes (decoding path/query/
// body and calling the same GreeterServer used by gRPC), and NewGreeterService
// packages both the gRPC and HTTP registration into a single server.Service so
// callers write no grpc.ServiceRegistrar / gin.Engine plumbing themselves.
package main

import (
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"

	onexmeshv1 "github.com/onexstack/onexmesh/pkg/proto/onexmesh/v1"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generate(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

// binding is the parsed HTTP mapping for a single method.
type binding struct {
	httpMethod string // GET / POST / PUT / DELETE / PATCH
	path       string // original path template, e.g. "/helloworld/{name}"
	hasBody    bool   // whether the request body is bound (body == "*")
}

func generate(gen *protogen.Plugin, file *protogen.File) error {
	type svcMethods struct {
		service *protogen.Service
		methods []*protogen.Method
	}

	var services []svcMethods
	for _, svc := range file.Services {
		var methods []*protogen.Method
		for _, m := range svc.Methods {
			if ruleOf(m) == nil {
				continue
			}
			methods = append(methods, m)
		}
		if len(methods) > 0 {
			services = append(services, svcMethods{service: svc, methods: methods})
		}
	}
	if len(services) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_http.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-onexmesh. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P("    \"net/http\"")
	g.P()
	g.P("    \"github.com/gin-gonic/gin\"")
	g.P("    \"google.golang.org/grpc\"")
	g.P()
	g.P("    \"github.com/onexstack/onexmesh/pkg/codec\"")
	g.P("    \"github.com/onexstack/onexmesh/pkg/server\"")
	g.P(")")
	g.P()

	for _, svc := range services {
		iface := svc.service.GoName + "Server"
		g.P("// Register", svc.service.GoName, "HTTPServer registers the HTTP routes for service ",
			svc.service.GoName, " on engine. Each route decodes path/query/body into the request message")
		g.P("// and calls the same ", iface, " implementation used by gRPC.")
		g.P("func Register", svc.service.GoName, "HTTPServer(e *gin.Engine, srv ", iface, ") {")
		for i, m := range svc.methods {
			b := parseBinding(m)
			g.P("    e.", b.httpMethod, "(\"", ginPath(b.path), "\", ", handlerName(svc.service, m, i), "(srv))")
		}
		g.P("}")
		g.P()

		g.P("// New", svc.service.GoName, "Service packages the gRPC and HTTP registration for service ",
			svc.service.GoName, " into a single server.Service backed by one implementation.")
		g.P("func New", svc.service.GoName, "Service(srv ", iface, ") server.Service {")
		g.P("    return server.Service{")
		g.P("        Name: ", svc.service.GoName, "_ServiceDesc.ServiceName,")
		g.P("        Register: func(s grpc.ServiceRegistrar) {")
		g.P("            Register", svc.service.GoName, "Server(s, srv)")
		g.P("        },")
		g.P("        RegisterHTTP: func(e *gin.Engine) {")
		g.P("            Register", svc.service.GoName, "HTTPServer(e, srv)")
		g.P("        },")
		g.P("    }")
		g.P("}")
		g.P()

		for i, m := range svc.methods {
			emitHandler(g, svc.service, m, i, parseBinding(m))
		}
	}
	return nil
}

// ruleOf reads the onexmesh.v1.http extension from a method's options, or nil.
func ruleOf(m *protogen.Method) *onexmeshv1.HttpRule {
	opts, ok := m.Desc.Options().(*descriptorpb.MethodOptions)
	if !ok || opts == nil {
		return nil
	}
	if rule, ok := proto.GetExtension(opts, onexmeshv1.E_Http).(*onexmeshv1.HttpRule); ok && rule != nil {
		return rule
	}
	return nil
}

// parseBinding extracts the HTTP verb, path template and body flag from a rule.
func parseBinding(m *protogen.Method) binding {
	rule := ruleOf(m)
	b := binding{}
	switch {
	case rule.GetGet() != "":
		b.httpMethod, b.path = "GET", rule.GetGet()
	case rule.GetPut() != "":
		b.httpMethod, b.path = "PUT", rule.GetPut()
	case rule.GetPost() != "":
		b.httpMethod, b.path = "POST", rule.GetPost()
	case rule.GetDelete() != "":
		b.httpMethod, b.path = "DELETE", rule.GetDelete()
	case rule.GetPatch() != "":
		b.httpMethod, b.path = "PATCH", rule.GetPatch()
	}
	b.hasBody = rule.GetBody() == "*"
	return b
}

// ginPath converts a grpc-gateway-style path template "{field}" into gin's
// ":field" (or "*field" for the "{field=.../*}" multi-segment form).
func ginPath(template string) string {
	var b strings.Builder
	for i := 0; i < len(template); i++ {
		if template[i] != '{' {
			b.WriteByte(template[i])
			continue
		}
		end := strings.IndexByte(template[i:], '}')
		if end < 0 {
			b.WriteByte(template[i])
			continue
		}
		field := template[i+1 : i+end]
		if eq := strings.IndexByte(field, '='); eq >= 0 {
			b.WriteByte('*')
			b.WriteString(field[:eq])
		} else {
			b.WriteByte(':')
			b.WriteString(field)
		}
		i += end
	}
	return b.String()
}

// handlerName returns the Go identifier for a method's HTTP handler, e.g.
// _Greeter_SayHello0_HTTP_Handler.
func handlerName(svc *protogen.Service, m *protogen.Method, idx int) string {
	return "_" + svc.GoName + "_" + m.GoName + strconv.Itoa(idx) + "_HTTP_Handler"
}

// emitHandler writes the gin.HandlerFunc for a method.
func emitHandler(g *protogen.GeneratedFile, svc *protogen.Service, m *protogen.Method, idx int, b binding) {
	iface := svc.GoName + "Server"
	in := m.Input.GoIdent.GoName
	handler := handlerName(svc, m, idx)

	g.P("func ", handler, "(srv ", iface, ") gin.HandlerFunc {")
	g.P("    return func(c *gin.Context) {")
	g.P("        var in ", in)
	g.P("        if err := codec.BindPath(c, &in, \"", b.path, "\"); err != nil {")
	g.P("            codec.RenderError(c, err)")
	g.P("            return")
	g.P("        }")
	g.P("        if err := codec.BindQuery(c, &in); err != nil {")
	g.P("            codec.RenderError(c, err)")
	g.P("            return")
	g.P("        }")
	if b.hasBody {
		g.P("        if err := codec.Bind(c, &in); err != nil {")
		g.P("            codec.RenderError(c, err)")
		g.P("            return")
		g.P("        }")
	}
	g.P("        out, err := srv.", m.GoName, "(c.Request.Context(), &in)")
	g.P("        if err != nil {")
	g.P("            codec.RenderError(c, err)")
	g.P("            return")
	g.P("        }")
	g.P("        codec.Render(c, http.StatusOK, out)")
	g.P("    }")
	g.P("}")
	g.P()
}
