// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Command protoc-gen-onexmesh is a protoc plugin that generates HTTP route
// descriptors for a service whose methods carry the onexmesh.v1.http annotation
// (see pkg/proto/onexmesh/v1/http.proto).
//
// For an annotated method:
//
//	service Greeter {
//	  rpc SayHello(HelloRequest) returns (HelloReply) {
//	    option (onexmesh.v1.http) = { get: "/helloworld/{name}" };
//	  }
//	}
//
// it emits a *_http.pb.go with a single factory:
//
//	func NewGreeterService(srv GreeterServer) server.Service
//
// The returned server.Service declares proto-first Methods whose request/response
// types are enforced to be protobuf at compile time, plus the generated gRPC
// RegisterXxxServer bridge. A single srv.SayHello function therefore serves both
// protocols; the HTTP binding (path/query/body) is performed by the shared
// codec.BindHTTP runtime rather than per-method hand-written handlers.
package main

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"

	onexmeshv1 "github.com/onexstack/onexmesh/pkg/proto/onexmesh/v1"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generate(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

// binding is the parsed HTTP mapping for a single method.
type binding struct {
	httpMethod string // GET / POST / PUT / DELETE / PATCH
	path       string // original path template, e.g. "/helloworld/{name}"
	body       string // "*" when the whole message is the body, "" otherwise
}

func generate(gen *protogen.Plugin, file *protogen.File) error {
	type svcMethods struct {
		service *protogen.Service
		methods []*protogen.Method
	}

	var services []svcMethods
	for _, svc := range file.Services {
		var methods []*protogen.Method
		for _, m := range svc.Methods {
			if ruleOf(m) == nil {
				continue
			}
			// A streaming RPC cannot be served by the unary handler NewMethod
			// expects: srv.<M> would be func(*Req, XxxServer) error (or the
			// client-stream shapes), which does not unify with
			// func(context.Context, Req) (Resp, error). Emitting it anyway would
			// surface as a generic-inference error inside the generated file, far
			// from the annotation that caused it.
			if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
				gen.Error(fmt.Errorf(
					"%s.%s: onexmesh.v1.http cannot annotate a streaming method", svc.GoName, m.GoName,
				))
				continue
			}
			// parseBinding matches the verb by testing one field at a time, so a
			// rule carrying an unsupported verb (or none at all) binds an empty
			// method. Method.Apply registers it via gin's Handle, which panics at
			// startup on an empty verb; reject it at generation time instead.
			if b := parseBinding(m); b.httpMethod == "" {
				gen.Error(fmt.Errorf(
					"%s.%s: onexmesh.v1.http must set one of get/put/post/delete/patch", svc.GoName, m.GoName,
				))
				continue
			}
			methods = append(methods, m)
		}
		if len(methods) > 0 {
			services = append(services, svcMethods{service: svc, methods: methods})
		}
	}
	if len(services) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_http.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-onexmesh. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// Resolve the framework package qualifiers up front. QualifiedGoIdent records
	// their imports (and any well-known request types) so protogen emits a single
	// correct import block rather than a hand-written one that cannot account for
	// types such as google.protobuf.Empty.
	serviceRegistrar := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "google.golang.org/grpc", GoName: "ServiceRegistrar"})
	serverService := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/onexstack/onexmesh/pkg/server", GoName: "Service"})
	serverMethod := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/onexstack/onexmesh/pkg/server", GoName: "Method"})
	serverNewMethod := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "github.com/onexstack/onexmesh/pkg/server", GoName: "NewMethod"})
	g.P()

	for _, svc := range services {
		iface := svc.service.GoName + "Server"

		g.P("// New", svc.service.GoName, "Service packages the gRPC and HTTP registration for service ",
			svc.service.GoName, " into a single ", serverService, " backed by one implementation.")
		g.P("// Each Method is proto-first: its request/response are protobuf messages and its Handler is the same ",
			iface, " method used by gRPC.")
		g.P("func New", svc.service.GoName, "Service(srv ", iface, ") ", serverService, " {")
		g.P("    return ", serverService, "{")
		g.P("        Name: ", svc.service.GoName, "_ServiceDesc.ServiceName,")
		g.P("        Register: func(s ", serviceRegistrar, ") {")
		g.P("            Register", svc.service.GoName, "Server(s, srv)")
		g.P("        },")
		g.P("        Methods: []", serverMethod, "{")
		for _, m := range svc.methods {
			b := parseBinding(m)
			g.P("            ", serverNewMethod, "(\"", m.GoName, "\", \"", b.httpMethod, "\", \"", b.path, "\", \"", b.body,
				"\", srv.", m.GoName, "),")
		}
		g.P("        },")
		g.P("    }")
		g.P("}")
		g.P()
	}
	return nil
}

// ruleOf reads the onexmesh.v1.http extension from a method's options, or nil.
func ruleOf(m *protogen.Method) *onexmeshv1.HttpRule {
	opts, ok := m.Desc.Options().(*descriptorpb.MethodOptions)
	if !ok || opts == nil {
		return nil
	}
	if rule, ok := proto.GetExtension(opts, onexmeshv1.E_Http).(*onexmeshv1.HttpRule); ok && rule != nil {
		return rule
	}
	return nil
}

// parseBinding extracts the HTTP verb, path template and body flag from a rule.
func parseBinding(m *protogen.Method) binding {
	rule := ruleOf(m)
	b := binding{}
	switch {
	case rule.GetGet() != "":
		b.httpMethod, b.path = "GET", rule.GetGet()
	case rule.GetPut() != "":
		b.httpMethod, b.path = "PUT", rule.GetPut()
	case rule.GetPost() != "":
		b.httpMethod, b.path = "POST", rule.GetPost()
	case rule.GetDelete() != "":
		b.httpMethod, b.path = "DELETE", rule.GetDelete()
	case rule.GetPatch() != "":
		b.httpMethod, b.path = "PATCH", rule.GetPatch()
	}
	if rule.GetBody() == "*" {
		b.body = "*"
	}
	return b
}
