// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Package scheme generates the clientset scheme/register.go, which aggregates
// the AddToScheme of every group/version into a single runtime.Scheme.
package scheme

import (
	"fmt"
	"strings"

	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/spec"
)

// Generate renders the clientset scheme/register.go.
func Generate(s *spec.Spec) string {
	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "package scheme\n\n")
	b.WriteString(importHeader)

	// Group/version imports with aliases.
	for _, g := range s.Groups {
		for _, vs := range g.Versions {
			fmt.Fprintf(&b, "\t%s %q\n", versionAlias(g, vs), vs.GoPackage)
		}
	}
	b.WriteString("\tmetav1 \"k8s.io/apimachinery/pkg/apis/meta/v1\"\n")
	b.WriteString("\truntime \"k8s.io/apimachinery/pkg/runtime\"\n")
	b.WriteString("\tschema \"k8s.io/apimachinery/pkg/runtime/schema\"\n")
	b.WriteString("\tserializer \"k8s.io/apimachinery/pkg/runtime/serializer\"\n")
	b.WriteString("\tutilruntime \"k8s.io/apimachinery/pkg/util/runtime\"\n")
	b.WriteString(")\n\n")

	b.WriteString("var Scheme = runtime.NewScheme()\n")
	b.WriteString("var Codecs = serializer.NewCodecFactory(Scheme)\n")
	b.WriteString("var ParameterCodec = runtime.NewParameterCodec(Scheme)\n")
	b.WriteString("var localSchemeBuilder = runtime.SchemeBuilder{\n")
	for _, g := range s.Groups {
		for _, vs := range g.Versions {
			fmt.Fprintf(&b, "\t%s.AddToScheme,\n", versionAlias(g, vs))
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("// AddToScheme adds all types of this clientset into the given scheme.\n")
	b.WriteString("var AddToScheme = localSchemeBuilder.AddToScheme\n\n")

	b.WriteString("func init() {\n")
	// Register the core meta group.
	b.WriteString("\tmetav1.AddToGroupVersion(Scheme, schema.GroupVersion{Version: \"v1\"})\n")
	b.WriteString("\tutilruntime.Must(AddToScheme(Scheme))\n")
	b.WriteString("}\n")

	return b.String()
}

const header = `// Code generated by protoc-gen-onexmesh-client. DO NOT EDIT.

`

const importHeader = `import (
`

// versionAlias returns the import alias for a group/version, e.g. "appsv1".
func versionAlias(g *spec.GroupSpec, vs *spec.VersionSpec) string {
	return strings.ToLower(g.GroupGoName) + vs.Version
}
