// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Package meshmeta defines the runtime metadata types used by generated REST
// SDK object types. These mirror k8s.io/apimachinery/pkg/apis/meta/v1 but are
// generated with the modern protoc-gen-go so that generated resource messages
// can reference them as message fields (the Kubernetes meta types are
// gogo-protobuf generated and cannot be referenced by modern protoc output).
//
// IMPORTANT: field names intentionally use the camelCase convention (rather
// than the protobuf snake_case convention) so that the generated Go json tags
// match the Kubernetes JSON wire format. protoc-gen-go emits a json tag equal
// to the proto field name; snake_case field names would produce snake_case
// JSON keys, which diverge from client-go.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pkg/proto/onexmesh/meta/v1/meta.proto

package meshmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypeMeta carries apiVersion and kind, mirroring metav1.TypeMeta.
type TypeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeMeta) Reset() {
	*x = TypeMeta{}
	mi := &file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeMeta) ProtoMessage() {}

func (x *TypeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeMeta.ProtoReflect.Descriptor instead.
func (*TypeMeta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDescGZIP(), []int{0}
}

func (x *TypeMeta) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *TypeMeta) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// ObjectMeta mirrors metav1.ObjectMeta.
//
// ownerReferences and managedFields are intentionally omitted in the first
// iteration; the generated meta adapter returns empty values for them.
type ObjectMeta struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Name                       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GenerateName               string                 `protobuf:"bytes,2,opt,name=generateName,proto3" json:"generateName,omitempty"`
	Namespace                  string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SelfLink                   string                 `protobuf:"bytes,4,opt,name=selfLink,proto3" json:"selfLink,omitempty"`
	Uid                        string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	ResourceVersion            string                 `protobuf:"bytes,6,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	Generation                 int64                  `protobuf:"varint,7,opt,name=generation,proto3" json:"generation,omitempty"`
	CreationTimestamp          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=creationTimestamp,proto3" json:"creationTimestamp,omitempty"`
	DeletionTimestamp          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deletionTimestamp,proto3" json:"deletionTimestamp,omitempty"`
	DeletionGracePeriodSeconds *int64                 `protobuf:"varint,10,opt,name=deletionGracePeriodSeconds,proto3,oneof" json:"deletionGracePeriodSeconds,omitempty"`
	Labels                     map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations                map[string]string      `protobuf:"bytes,12,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Finalizers                 []string               `protobuf:"bytes,13,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetGenerateName() string {
	if x != nil {
		return x.GenerateName
	}
	return ""
}

func (x *ObjectMeta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ObjectMeta) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

func (x *ObjectMeta) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ObjectMeta) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *ObjectMeta) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ObjectMeta) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

func (x *ObjectMeta) GetDeletionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTimestamp
	}
	return nil
}

func (x *ObjectMeta) GetDeletionGracePeriodSeconds() int64 {
	if x != nil && x.DeletionGracePeriodSeconds != nil {
		return *x.DeletionGracePeriodSeconds
	}
	return 0
}

func (x *ObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectMeta) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ObjectMeta) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

// ListMeta mirrors metav1.ListMeta.
type ListMeta struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourceVersion    string                 `protobuf:"bytes,1,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	Continue           string                 `protobuf:"bytes,2,opt,name=continue,proto3" json:"continue,omitempty"`
	RemainingItemCount *int64                 `protobuf:"varint,3,opt,name=remainingItemCount,proto3,oneof" json:"remainingItemCount,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListMeta) Reset() {
	*x = ListMeta{}
	mi := &file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeta) ProtoMessage() {}

func (x *ListMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeta.ProtoReflect.Descriptor instead.
func (*ListMeta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDescGZIP(), []int{2}
}

func (x *ListMeta) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *ListMeta) GetContinue() string {
	if x != nil {
		return x.Continue
	}
	return ""
}

func (x *ListMeta) GetRemainingItemCount() int64 {
	if x != nil && x.RemainingItemCount != nil {
		return *x.RemainingItemCount
	}
	return 0
}

var File_pkg_proto_onexmesh_meta_v1_meta_proto protoreflect.FileDescriptor

const file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDesc = "" +
	"\n" +
	"%pkg/proto/onexmesh/meta/v1/meta.proto\x12\x10onexmesh.meta.v1\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\bTypeMeta\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"\x80\x06\n" +
	"\n" +
	"ObjectMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fgenerateName\x18\x02 \x01(\tR\fgenerateName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bselfLink\x18\x04 \x01(\tR\bselfLink\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12(\n" +
	"\x0fresourceVersion\x18\x06 \x01(\tR\x0fresourceVersion\x12\x1e\n" +
	"\n" +
	"generation\x18\a \x01(\x03R\n" +
	"generation\x12H\n" +
	"\x11creationTimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11creationTimestamp\x12H\n" +
	"\x11deletionTimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x11deletionTimestamp\x12C\n" +
	"\x1adeletionGracePeriodSeconds\x18\n" +
	" \x01(\x03H\x00R\x1adeletionGracePeriodSeconds\x88\x01\x01\x12@\n" +
	"\x06labels\x18\v \x03(\v2(.onexmesh.meta.v1.ObjectMeta.LabelsEntryR\x06labels\x12O\n" +
	"\vannotations\x18\f \x03(\v2-.onexmesh.meta.v1.ObjectMeta.AnnotationsEntryR\vannotations\x12\x1e\n" +
	"\n" +
	"finalizers\x18\r \x03(\tR\n" +
	"finalizers\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x1d\n" +
	"\x1b_deletionGracePeriodSeconds\"\x9c\x01\n" +
	"\bListMeta\x12(\n" +
	"\x0fresourceVersion\x18\x01 \x01(\tR\x0fresourceVersion\x12\x1a\n" +
	"\bcontinue\x18\x02 \x01(\tR\bcontinue\x123\n" +
	"\x12remainingItemCount\x18\x03 \x01(\x03H\x00R\x12remainingItemCount\x88\x01\x01B\x15\n" +
	"\x13_remainingItemCountBCZAgithub.com/onexstack/onexmesh/pkg/proto/onexmesh/meta/v1;meshmetab\x06proto3"

var (
	file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDescOnce sync.Once
	file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDescData []byte
)

func file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDescGZIP() []byte {
	file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDescOnce.Do(func() {
		file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDesc), len(file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDesc)))
	})
	return file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDescData
}

var file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_onexmesh_meta_v1_meta_proto_goTypes = []any{
	(*TypeMeta)(nil),              // 0: onexmesh.meta.v1.TypeMeta
	(*ObjectMeta)(nil),            // 1: onexmesh.meta.v1.ObjectMeta
	(*ListMeta)(nil),              // 2: onexmesh.meta.v1.ListMeta
	nil,                           // 3: onexmesh.meta.v1.ObjectMeta.LabelsEntry
	nil,                           // 4: onexmesh.meta.v1.ObjectMeta.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_pkg_proto_onexmesh_meta_v1_meta_proto_depIdxs = []int32{
	5, // 0: onexmesh.meta.v1.ObjectMeta.creationTimestamp:type_name -> google.protobuf.Timestamp
	5, // 1: onexmesh.meta.v1.ObjectMeta.deletionTimestamp:type_name -> google.protobuf.Timestamp
	3, // 2: onexmesh.meta.v1.ObjectMeta.labels:type_name -> onexmesh.meta.v1.ObjectMeta.LabelsEntry
	4, // 3: onexmesh.meta.v1.ObjectMeta.annotations:type_name -> onexmesh.meta.v1.ObjectMeta.AnnotationsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_onexmesh_meta_v1_meta_proto_init() }
func file_pkg_proto_onexmesh_meta_v1_meta_proto_init() {
	if File_pkg_proto_onexmesh_meta_v1_meta_proto != nil {
		return
	}
	file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDesc), len(file_pkg_proto_onexmesh_meta_v1_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_onexmesh_meta_v1_meta_proto_goTypes,
		DependencyIndexes: file_pkg_proto_onexmesh_meta_v1_meta_proto_depIdxs,
		MessageInfos:      file_pkg_proto_onexmesh_meta_v1_meta_proto_msgTypes,
	}.Build()
	File_pkg_proto_onexmesh_meta_v1_meta_proto = out.File
	file_pkg_proto_onexmesh_meta_v1_meta_proto_goTypes = nil
	file_pkg_proto_onexmesh_meta_v1_meta_proto_depIdxs = nil
}
