// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Command protoc-gen-errno is a protoc plugin that turns a proto enum into a
// semantic error catalog, one constructor per value.
//
// The catalog is expressed with the two extensions errno.proto declares:
//
//	enum UserStatus {
//	  option (onexmesh.errno.v1.default_code) = 400;   // for values without one
//	  Active = 0;
//	  Banned = 2 [(onexmesh.errno.v1.code) = 403];
//	}
//
// and for each value it emits a Reason constant plus an errorsx constructor:
//
//	var ReasonBanned = "Banned"
//	func ErrorBanned(msg string) *errorsx.ErrorX
//
// The file is named *_errno.pb.go after the annotated proto. A proto that
// declares no enum produces no file at all -- the plugin is additive, and a
// file with nothing to say would only be an empty package-level artifact.
//
// Two things are worth knowing before changing this plugin:
//
//   - (onexmesh.errno.v1.code) is optional, and so is the enum-level
//     default_code. A value that sets neither falls back to 500. That is not a
//     placeholder: a proto enum doubles as an error catalog precisely when a
//     value can be listed before its status code is decided, and an unclassified
//     value must still produce a constructor rather than be skipped.
//   - Consequently this plugin skips nothing. The sibling generator
//     protoc-gen-go-errors (Kratos) drops every value whose code is 0, which is
//     why its output and this one differ on the same input even though both walk
//     an enum the same way.
package main

import (
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/onexstack/onexmesh/pkg/errno"
)

// defaultCode is the status a value falls back to when neither its own
// (errno.code) nor its enum's (errno.default_code) names one. It matches
// http.StatusInternalServerError -- an error that reached a catalog without
// being classified is by definition one whose cause is not yet known.
const defaultCode = 500

// errorsxPath is where the emitted constructors' return type lives, and
// errorsxName is the package name the generated file refers to it by.
//
// The import is written into the output literally rather than through
// g.QualifiedGoIdent. protogen records an import path it cannot resolve with an
// explicit alias and emits it as a block --
//
//	import (
//		errorsx "github.com/onexstack/onexstack/pkg/errorsx"
//	)
//
// -- which is not the shape the committed *_errno.pb.go files have. There is
// exactly one import here and its package name is the path's last element, so
// writing it out is both exact and stable.
const (
	errorsxPath = "github.com/onexstack/onexstack/pkg/errorsx"
	errorsxName = "errorsx"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := generate(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

func generate(gen *protogen.Plugin, file *protogen.File) error {
	if len(file.Enums) == 0 {
		return nil
	}

	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_errno.pb.go", file.GoImportPath)

	g.P("// Code generated by protoc-gen-errno. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import ", quote(errorsxPath))
	g.P()

	// A blank line separates consecutive blocks, so it is emitted before every
	// block but the first -- which leaves no trailing blank line at EOF.
	first := true
	for _, enum := range file.Enums {
		code := defaultCode
		if v, ok := proto.GetExtension(enum.Desc.Options(), errno.E_DefaultCode).(int32); ok && v != 0 {
			code = int(v)
		}

		for _, value := range enum.Values {
			valueCode := code
			if v, ok := proto.GetExtension(value.Desc.Options(), errno.E_Code).(int32); ok && v != 0 {
				valueCode = int(v)
			}

			name := string(value.Desc.Name())
			camel := case2Camel(name)

			if !first {
				g.P()
			}
			first = false

			g.P("// Reason", camel, " is the semantic Reason for error ", camel, ".")
			g.P("var Reason", camel, " = ", quote(name))
			g.P()
			g.P("// Error", camel, " returns a ", camel, " error carrying the given message.")
			g.P("func Error", camel, "(msg string) *", errorsxName, ".ErrorX {")
			g.P("return ", errorsxName, ".New(", valueCode, ", Reason", camel, `, "%s", msg)`)
			g.P("}")
		}
	}

	return nil
}

// quote renders s as a double-quoted Go string literal. The value name reaches
// this file from a .proto identifier, so it is already restricted to letters,
// digits and underscores; quoting keeps that assumption explicit rather than
// relying on it.
func quote(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	b.WriteString(s)
	b.WriteByte('"')
	return b.String()
}

// case2Camel converts an enum value name to the CamelCase used in the generated
// identifiers: USER_NOT_FOUND and user_not_found both give UserNotFound, and a
// single word is title-cased, so active gives Active.
//
// A word with no lowercase letter of its own (an all-caps segment) is lowered
// first, which is what keeps USER_NOT_FOUND from becoming USERNOTFOUND. Words
// that already carry lowercase are left else as they are, so an existing Camel
// word such as GradYear survives unchanged.
//
// This mirrors protoc-gen-go-errors' conversion, deliberately: the two plugins
// are read side by side, and a value naming an enum should not change shape
// depending on which one produced the file.
func case2Camel(name string) string {
	if !strings.Contains(name, "_") {
		return titleWord(name)
	}
	parts := strings.Split(name, "_")
	words := make([]string, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		words = append(words, titleWord(p))
	}
	return strings.Join(words, "")
}

// titleWord upper-cases the first rune of a single word, lower-casing the whole
// word first when it carries no lowercase letter of its own.
func titleWord(w string) string {
	if w == "" {
		return w
	}
	if !hasLower(w) {
		w = strings.ToLower(w)
	}
	runes := []rune(w)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func hasLower(s string) bool {
	for _, r := range s {
		if unicode.IsLower(r) {
			return true
		}
	}
	return false
}
