// Code generated by protoc-gen-onexmesh. DO NOT EDIT.
// source: examples/helloworld/proto/hello.proto

package helloworld

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"google.golang.org/grpc"

	"github.com/onexstack/onexmesh/pkg/codec"
	"github.com/onexstack/onexmesh/pkg/server"
)

// RegisterGreeterHTTPServer registers the HTTP routes for service Greeter on engine. Each route decodes path/query/body into the request message
// and calls the same GreeterServer implementation used by gRPC.
func RegisterGreeterHTTPServer(e *gin.Engine, srv GreeterServer) {
	e.GET("/helloworld/:name", _Greeter_SayHello0_HTTP_Handler(srv))
	e.POST("/helloworld", _Greeter_SayHelloPost1_HTTP_Handler(srv))
}

// NewGreeterService packages the gRPC and HTTP registration for service Greeter into a single server.Service backed by one implementation.
func NewGreeterService(srv GreeterServer) server.Service {
	return server.Service{
		Name: Greeter_ServiceDesc.ServiceName,
		Register: func(s grpc.ServiceRegistrar) {
			RegisterGreeterServer(s, srv)
		},
		RegisterHTTP: func(e *gin.Engine) {
			RegisterGreeterHTTPServer(e, srv)
		},
	}
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in HelloRequest
		if err := codec.BindPath(c, &in, "/helloworld/{name}"); err != nil {
			codec.RenderError(c, err)
			return
		}
		if err := codec.BindQuery(c, &in); err != nil {
			codec.RenderError(c, err)
			return
		}
		out, err := srv.SayHello(c.Request.Context(), &in)
		if err != nil {
			codec.RenderError(c, err)
			return
		}
		codec.Render(c, http.StatusOK, out)
	}
}

func _Greeter_SayHelloPost1_HTTP_Handler(srv GreeterServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in HelloRequest
		if err := codec.BindPath(c, &in, "/helloworld"); err != nil {
			codec.RenderError(c, err)
			return
		}
		if err := codec.BindQuery(c, &in); err != nil {
			codec.RenderError(c, err)
			return
		}
		if err := codec.Bind(c, &in); err != nil {
			codec.RenderError(c, err)
			return
		}
		out, err := srv.SayHelloPost(c.Request.Context(), &in)
		if err != nil {
			codec.RenderError(c, err)
			return
		}
		codec.Render(c, http.StatusOK, out)
	}
}
