// Code generated by protoc-gen-onexmesh. DO NOT EDIT.
// source: examples/helloworld/proto/hello.proto

package helloworld

import (
	server "github.com/onexstack/onexmesh/pkg/server"
	grpc "google.golang.org/grpc"
)

// NewGreeterService packages the gRPC and HTTP registration for service Greeter into a single server.Service backed by one implementation.
// Each Method is proto-first: its request/response are protobuf messages and its Handler is the same GreeterServer method used by gRPC.
func NewGreeterService(srv GreeterServer) server.Service {
	return server.Service{
		Name: Greeter_ServiceDesc.ServiceName,
		Register: func(s grpc.ServiceRegistrar) {
			RegisterGreeterServer(s, srv)
		},
		Methods: []server.Method{
			server.NewMethod("SayHello", "GET", "/helloworld/{name}", "", func() *HelloRequest { return &HelloRequest{} }, srv.SayHello),
			server.NewMethod("SayHelloPost", "POST", "/helloworld", "*", func() *HelloRequest { return &HelloRequest{} }, srv.SayHelloPost),
		},
	}
}
