// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Package mr provides a generic MapReduce with a bounded worker pool, guarded
// channel writes and first-error cancellation. It is modeled on go-zero's core/mr
// so that fan-out/fan-in data processing can be expressed without manual
// goroutine and channel plumbing.
package mr

import (
	"context"
	"errors"
	"fmt"
	"runtime/debug"
	"strings"
	"sync"
	"sync/atomic"
)

const (
	defaultWorkers = 16
	minWorkers     = 1
)

var (
	// ErrCancelWithNil is returned when a mapper/reducer cancels with a nil error.
	ErrCancelWithNil = errors.New("mr: cancelled with nil")
	// ErrReduceNoOutput is returned when the reducer writes no value.
	ErrReduceNoOutput = errors.New("mr: reducer wrote no value")
)

type (
	// ForEachFunc processes an element without producing output.
	ForEachFunc[T any] func(item T)
	// GenerateFunc sends input elements into source.
	GenerateFunc[T any] func(source chan<- T)
	// MapFunc processes an element and writes output to the writer.
	MapFunc[T, U any] func(item T, writer Writer[U])
	// MapperFunc processes an element and writes output, or cancels processing.
	MapperFunc[T, U any] func(item T, writer Writer[U], cancel func(error))
	// ReducerFunc reduces the mapper outputs into a single value, or cancels.
	ReducerFunc[U, V any] func(pipe <-chan U, writer Writer[V], cancel func(error))
	// VoidReducerFunc reduces the mapper outputs without producing a value.
	VoidReducerFunc[U any] func(pipe <-chan U, cancel func(error))
	// Option customizes a MapReduce.
	Option func(opts *mapReduceOptions)

	// Writer wraps Write, the sink used by mappers and reducers.
	Writer[T any] interface {
		Write(v T)
	}

	mapperContext[T, U any] struct {
		ctx       context.Context
		mapper    MapFunc[T, U]
		source    <-chan T
		panicChan *onceChan
		collector chan<- U
		doneChan  <-chan struct{}
		workers   int
	}

	mapReduceOptions struct {
		ctx     context.Context
		workers int
	}
)

// WithWorkers sets the number of worker goroutines (minimum 1).
func WithWorkers(workers int) Option {
	return func(opts *mapReduceOptions) {
		if workers < minWorkers {
			opts.workers = minWorkers
		} else {
			opts.workers = workers
		}
	}
}

// WithContext makes the processing honor the given context.
func WithContext(ctx context.Context) Option {
	return func(opts *mapReduceOptions) { opts.ctx = ctx }
}

// MapReduce maps all elements generated by generate, then reduces the outputs
// with reducer.
func MapReduce[T, U, V any](generate GenerateFunc[T], mapper MapperFunc[T, U], reducer ReducerFunc[U, V],
	opts ...Option) (V, error) {
	panicChan := &onceChan{channel: make(chan any)}
	source := buildSource(generate, panicChan)
	return mapReduceWithPanicChan(source, panicChan, mapper, reducer, opts...)
}

// MapReduceChan is MapReduce over an existing source channel.
func MapReduceChan[T, U, V any](source <-chan T, mapper MapperFunc[T, U], reducer ReducerFunc[U, V],
	opts ...Option) (V, error) {
	panicChan := &onceChan{channel: make(chan any)}
	return mapReduceWithPanicChan(source, panicChan, mapper, reducer, opts...)
}

// ForEach maps all elements generated by generate with no output.
func ForEach[T any](generate GenerateFunc[T], mapper ForEachFunc[T], opts ...Option) {
	options := buildOptions(opts...)
	panicChan := &onceChan{channel: make(chan any)}
	source := buildSource(generate, panicChan)
	collector := make(chan any)
	done := make(chan struct{})

	go executeMappers(mapperContext[T, any]{
		ctx: options.ctx,
		mapper: func(item T, _ Writer[any]) {
			mapper(item)
		},
		source:    source,
		panicChan: panicChan,
		collector: collector,
		doneChan:  done,
		workers:   options.workers,
	})

	for {
		select {
		case v := <-panicChan.channel:
			panic(v)
		case _, ok := <-collector:
			if !ok {
				return
			}
		}
	}
}

// Finish runs fns in parallel, cancelling on the first error.
func Finish(fns ...func() error) error {
	if len(fns) == 0 {
		return nil
	}
	_, err := MapReduce(
		func(source chan<- func() error) {
			for _, fn := range fns {
				source <- fn
			}
		},
		func(fn func() error, _ Writer[any], cancel func(error)) {
			if err := fn(); err != nil {
				cancel(err)
			}
		},
		func(_ <-chan any, _ Writer[any], _ func(error)) {},
		WithWorkers(len(fns)),
	)
	if errors.Is(err, ErrReduceNoOutput) {
		return nil
	}
	return err
}

// FinishVoid runs fns in parallel and ignores errors.
func FinishVoid(fns ...func()) {
	if len(fns) == 0 {
		return
	}
	ForEach(
		func(source chan<- func()) {
			for _, fn := range fns {
				source <- fn
			}
		},
		func(fn func()) { fn() },
		WithWorkers(len(fns)),
	)
}

func buildOptions(opts ...Option) *mapReduceOptions {
	options := &mapReduceOptions{ctx: context.Background(), workers: defaultWorkers}
	for _, opt := range opts {
		opt(options)
	}
	return options
}

func buildSource[T any](generate GenerateFunc[T], panicChan *onceChan) chan T {
	source := make(chan T)
	go func() {
		defer func() {
			if r := recover(); r != nil {
				panicChan.write(buildPanicInfo(r))
			}
			close(source)
		}()
		generate(source)
	}()
	return source
}

func executeMappers[T, U any](mCtx mapperContext[T, U]) {
	var wg sync.WaitGroup
	defer func() {
		wg.Wait()
		close(mCtx.collector)
		drain(mCtx.source)
	}()

	var failed int32
	pool := make(chan struct{}, mCtx.workers)
	writer := newGuardedWriter(mCtx.ctx, mCtx.collector, mCtx.doneChan)
	for atomic.LoadInt32(&failed) == 0 {
		select {
		case <-mCtx.ctx.Done():
			return
		case <-mCtx.doneChan:
			return
		case pool <- struct{}{}:
			item, ok := <-mCtx.source
			if !ok {
				<-pool
				return
			}
			wg.Add(1)
			go func() {
				defer func() {
					if r := recover(); r != nil {
						atomic.AddInt32(&failed, 1)
						mCtx.panicChan.write(buildPanicInfo(r))
					}
					wg.Done()
					<-pool
				}()
				mCtx.mapper(item, writer)
			}()
		}
	}
}

func mapReduceWithPanicChan[T, U, V any](source <-chan T, panicChan *onceChan, mapper MapperFunc[T, U],
	reducer ReducerFunc[U, V], opts ...Option) (val V, err error) {
	options := buildOptions(opts...)
	output := make(chan V)
	defer func() {
		// A reducer may only write once; extra writes panic.
		for range output {
			panic("mr: more than one element written in reducer")
		}
	}()

	collector := make(chan U, options.workers)
	done := make(chan struct{})
	writer := newGuardedWriter(options.ctx, output, done)
	var closeOnce sync.Once
	var retErr atomicError
	finish := func() {
		closeOnce.Do(func() {
			close(done)
			close(output)
		})
	}
	cancel := once(func(err error) {
		if err != nil {
			retErr.Set(err)
		} else {
			retErr.Set(ErrCancelWithNil)
		}
		drain(source)
		finish()
	})

	go func() {
		defer func() {
			drain(collector)
			if r := recover(); r != nil {
				panicChan.write(buildPanicInfo(r))
			}
			finish()
		}()
		reducer(collector, writer, cancel)
	}()

	go executeMappers(mapperContext[T, U]{
		ctx: options.ctx,
		mapper: func(item T, w Writer[U]) {
			mapper(item, w, cancel)
		},
		source:    source,
		panicChan: panicChan,
		collector: collector,
		doneChan:  done,
		workers:   options.workers,
	})

	select {
	case <-options.ctx.Done():
		cancel(context.DeadlineExceeded)
		err = context.DeadlineExceeded
	case v := <-panicChan.channel:
		drain(output)
		panic(v)
	case v, ok := <-output:
		if e := retErr.Load(); e != nil {
			err = e
		} else if ok {
			val = v
		} else {
			err = ErrReduceNoOutput
		}
	}
	return
}

func buildPanicInfo(r any) string {
	return fmt.Sprintf("%+v\n\n%s", r, strings.TrimSpace(string(debug.Stack())))
}

func drain[T any](channel <-chan T) {
	for range channel {
	}
}

func once(fn func(error)) func(error) {
	var o sync.Once
	return func(err error) {
		o.Do(func() { fn(err) })
	}
}

type guardedWriter[T any] struct {
	ctx     context.Context
	channel chan<- T
	done    <-chan struct{}
}

func newGuardedWriter[T any](ctx context.Context, channel chan<- T, done <-chan struct{}) guardedWriter[T] {
	return guardedWriter[T]{ctx: ctx, channel: channel, done: done}
}

func (gw guardedWriter[T]) Write(v T) {
	select {
	case <-gw.ctx.Done():
	case <-gw.done:
	default:
		gw.channel <- v
	}
}

type onceChan struct {
	channel chan any
	wrote   int32
}

func (oc *onceChan) write(val any) {
	if atomic.CompareAndSwapInt32(&oc.wrote, 0, 1) {
		oc.channel <- val
	}
}

// atomicError is a minimal thread-safe error holder.
type atomicError struct {
	err atomic.Value
}

func (e *atomicError) Set(err error) { e.err.Store(err) }

func (e *atomicError) Load() error {
	v := e.err.Load()
	if v == nil {
		return nil
	}
	return v.(error)
}
