// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

package informer

import (
	"fmt"
	"strings"

	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/spec"
)

// GenerateFactory renders informers/factory.go.
func GenerateFactory(s *spec.Spec) string {
	clientset := s.ClientsetPackageName
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package informers\n\n")
	b.WriteString("import (\n")
	b.WriteString("\tcontext \"context\"\n")
	b.WriteString("\treflect \"reflect\"\n")
	b.WriteString("\tsync \"sync\"\n")
	b.WriteString("\ttime \"time\"\n\n")
	b.WriteString("\tv1 \"k8s.io/apimachinery/pkg/apis/meta/v1\"\n")
	b.WriteString("\truntime \"k8s.io/apimachinery/pkg/runtime\"\n")
	b.WriteString("\tschema \"k8s.io/apimachinery/pkg/runtime/schema\"\n")
	b.WriteString("\twait \"k8s.io/apimachinery/pkg/util/wait\"\n")
	for _, g := range s.Groups {
		fmt.Fprintf(&b, "\t%s %q\n", groupPkgName(g), groupInformerPath(s, g))
	}
	fmt.Fprintf(&b, "\tinternalinterfaces %q\n", informersRoot(s)+"/internalinterfaces")
	fmt.Fprintf(&b, "\t%s %q\n", clientset, s.ClientsetGoPackage)
	b.WriteString("\tcache \"k8s.io/client-go/tools/cache\"\n")
	b.WriteString(")\n\n")

	b.WriteString("// SharedInformerOption defines the functional option type for SharedInformerFactory.\n")
	b.WriteString("type SharedInformerOption func(*sharedInformerFactory) *sharedInformerFactory\n\n")

	b.WriteString("type sharedInformerFactory struct {\n")
	fmt.Fprintf(&b, "\tclient           %s.Interface\n", clientset)
	b.WriteString("\tnamespace        string\n")
	b.WriteString("\ttweakListOptions internalinterfaces.TweakListOptionsFunc\n")
	b.WriteString("\tlock             sync.Mutex\n")
	b.WriteString("\tdefaultResync    time.Duration\n")
	b.WriteString("\tcustomResync     map[reflect.Type]time.Duration\n")
	b.WriteString("\ttransform        cache.TransformFunc\n")
	b.WriteString("\tinformerName     *cache.InformerName\n\n")
	b.WriteString("\tinformers map[reflect.Type]cache.SharedIndexInformer\n")
	b.WriteString("\t// startedInformers is used for tracking which informers have been started.\n")
	b.WriteString("\t// This allows Start() to be called multiple times safely.\n")
	b.WriteString("\tstartedInformers map[reflect.Type]bool\n")
	b.WriteString("\t// wg tracks how many goroutines were started.\n")
	b.WriteString("\twg sync.WaitGroup\n")
	b.WriteString("\t// shuttingDown is true when Shutdown has been called. It may still be running\n")
	b.WriteString("\t// because it needs to wait for goroutines.\n")
	b.WriteString("\tshuttingDown bool\n")
	b.WriteString("}\n\n")

	b.WriteString("// WithCustomResyncConfig sets a custom resync period for the specified informer types.\n")
	b.WriteString("func WithCustomResyncConfig(resyncConfig map[v1.Object]time.Duration) SharedInformerOption {\n")
	b.WriteString("\treturn func(factory *sharedInformerFactory) *sharedInformerFactory {\n")
	b.WriteString("\t\tfor k, v := range resyncConfig {\n")
	b.WriteString("\t\t\tfactory.customResync[reflect.TypeOf(k)] = v\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn factory\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("// WithTweakListOptions sets a custom filter on all listers of the configured SharedInformerFactory.\n")
	b.WriteString("func WithTweakListOptions(tweakListOptions internalinterfaces.TweakListOptionsFunc) SharedInformerOption {\n")
	b.WriteString("\treturn func(factory *sharedInformerFactory) *sharedInformerFactory {\n")
	b.WriteString("\t\tfactory.tweakListOptions = tweakListOptions\n")
	b.WriteString("\t\treturn factory\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("// WithNamespace limits the SharedInformerFactory to the specified namespace.\n")
	b.WriteString("func WithNamespace(namespace string) SharedInformerOption {\n")
	b.WriteString("\treturn func(factory *sharedInformerFactory) *sharedInformerFactory {\n")
	b.WriteString("\t\tfactory.namespace = namespace\n")
	b.WriteString("\t\treturn factory\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("// WithTransform sets a transform on all informers.\n")
	b.WriteString("func WithTransform(transform cache.TransformFunc) SharedInformerOption {\n")
	b.WriteString("\treturn func(factory *sharedInformerFactory) *sharedInformerFactory {\n")
	b.WriteString("\t\tfactory.transform = transform\n")
	b.WriteString("\t\treturn factory\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("// WithInformerName sets the InformerName for informer identity used in metrics.\n")
	b.WriteString("// The InformerName must be created via cache.NewInformerName() at startup,\n")
	b.WriteString("// which validates global uniqueness. Each informer type will register its\n")
	b.WriteString("// GVR under this name.\n")
	b.WriteString("func WithInformerName(informerName *cache.InformerName) SharedInformerOption {\n")
	b.WriteString("\treturn func(factory *sharedInformerFactory) *sharedInformerFactory {\n")
	b.WriteString("\t\tfactory.informerName = informerName\n")
	b.WriteString("\t\treturn factory\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("func (f *sharedInformerFactory) InformerName() *cache.InformerName {\n")
	b.WriteString("\treturn f.informerName\n")
	b.WriteString("}\n\n")

	b.WriteString("// NewSharedInformerFactory constructs a new instance of sharedInformerFactory for all namespaces.\n")
	fmt.Fprintf(&b, "func NewSharedInformerFactory(client %s.Interface, defaultResync time.Duration) SharedInformerFactory {\n", clientset)
	b.WriteString("\treturn NewSharedInformerFactoryWithOptions(client, defaultResync)\n")
	b.WriteString("}\n\n")

	b.WriteString("// NewFilteredSharedInformerFactory constructs a new instance of sharedInformerFactory.\n")
	b.WriteString("// Listers obtained via this SharedInformerFactory will be subject to the same filters\n")
	b.WriteString("// as specified here.\n//\n")
	b.WriteString("// Deprecated: Please use NewSharedInformerFactoryWithOptions instead\n")
	fmt.Fprintf(&b, "func NewFilteredSharedInformerFactory(client %s.Interface, defaultResync time.Duration, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) SharedInformerFactory {\n", clientset)
	b.WriteString("\treturn NewSharedInformerFactoryWithOptions(client, defaultResync, WithNamespace(namespace), WithTweakListOptions(tweakListOptions))\n")
	b.WriteString("}\n\n")

	b.WriteString("// NewSharedInformerFactoryWithOptions constructs a new instance of a SharedInformerFactory with additional options.\n")
	fmt.Fprintf(&b, "func NewSharedInformerFactoryWithOptions(client %s.Interface, defaultResync time.Duration, options ...SharedInformerOption) SharedInformerFactory {\n", clientset)
	b.WriteString("\tfactory := &sharedInformerFactory{\n")
	fmt.Fprintf(&b, "\t\tclient:           client,\n")
	b.WriteString("\t\tnamespace:        v1.NamespaceAll,\n")
	b.WriteString("\t\tdefaultResync:    defaultResync,\n")
	b.WriteString("\t\tinformers:        make(map[reflect.Type]cache.SharedIndexInformer),\n")
	b.WriteString("\t\tstartedInformers: make(map[reflect.Type]bool),\n")
	b.WriteString("\t\tcustomResync:     make(map[reflect.Type]time.Duration),\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\t// Apply all options\n")
	b.WriteString("\tfor _, opt := range options {\n")
	b.WriteString("\t\tfactory = opt(factory)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn factory\n")
	b.WriteString("}\n\n")

	b.WriteString("func (f *sharedInformerFactory) Start(stopCh <-chan struct{}) {\n")
	b.WriteString("\tf.StartWithContext(wait.ContextForChannel(stopCh))\n")
	b.WriteString("}\n\n")

	b.WriteString("func (f *sharedInformerFactory) StartWithContext(ctx context.Context) {\n")
	b.WriteString("\tf.lock.Lock()\n")
	b.WriteString("\tdefer f.lock.Unlock()\n\n")
	b.WriteString("\tif f.shuttingDown {\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tfor informerType, informer := range f.informers {\n")
	b.WriteString("\t\tif !f.startedInformers[informerType] {\n")
	b.WriteString("\t\t\tf.wg.Go(func() {\n")
	b.WriteString("\t\t\t\tinformer.RunWithContext(ctx)\n")
	b.WriteString("\t\t\t})\n")
	b.WriteString("\t\t\tf.startedInformers[informerType] = true\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("func (f *sharedInformerFactory) Shutdown() {\n")
	b.WriteString("\tf.lock.Lock()\n")
	b.WriteString("\tf.shuttingDown = true\n")
	b.WriteString("\tf.lock.Unlock()\n\n")
	b.WriteString("\t// Will return immediately if there is nothing to wait for.\n")
	b.WriteString("\tf.wg.Wait()\n")
	b.WriteString("\tf.informerName.Release()\n")
	b.WriteString("}\n\n")

	b.WriteString("func (f *sharedInformerFactory) WaitForCacheSync(stopCh <-chan struct{}) map[reflect.Type]bool {\n")
	b.WriteString("\tresult := f.WaitForCacheSyncWithContext(wait.ContextForChannel(stopCh))\n")
	b.WriteString("\treturn result.Synced\n")
	b.WriteString("}\n\n")

	b.WriteString("func (f *sharedInformerFactory) WaitForCacheSyncWithContext(ctx context.Context) cache.SyncResult {\n")
	b.WriteString("\tinformers := func() map[reflect.Type]cache.SharedIndexInformer {\n")
	b.WriteString("\t\tf.lock.Lock()\n")
	b.WriteString("\t\tdefer f.lock.Unlock()\n\n")
	b.WriteString("\t\tinformers := map[reflect.Type]cache.SharedIndexInformer{}\n")
	b.WriteString("\t\tfor informerType, informer := range f.informers {\n")
	b.WriteString("\t\t\tif f.startedInformers[informerType] {\n")
	b.WriteString("\t\t\t\tinformers[informerType] = informer\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn informers\n")
	b.WriteString("\t}()\n\n")
	b.WriteString("\t// Wait for informers to sync, without polling.\n")
	b.WriteString("\tcacheSyncs := make([]cache.DoneChecker, 0, len(informers))\n")
	b.WriteString("\tfor _, informer := range informers {\n")
	b.WriteString("\t\tcacheSyncs = append(cacheSyncs, informer.HasSyncedChecker())\n")
	b.WriteString("\t}\n")
	b.WriteString("\tcache.WaitFor(ctx, \"\" /* no logging */, cacheSyncs...)\n\n")
	b.WriteString("\tres := cache.SyncResult{\n")
	b.WriteString("\t\tSynced: make(map[reflect.Type]bool, len(informers)),\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfailed := false\n")
	b.WriteString("\tfor informType, informer := range informers {\n")
	b.WriteString("\t\thasSynced := informer.HasSynced()\n")
	b.WriteString("\t\tif !hasSynced {\n")
	b.WriteString("\t\t\tfailed = true\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tres.Synced[informType] = hasSynced\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif failed {\n")
	b.WriteString("\t\tres.Err = context.Cause(ctx)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn res\n")
	b.WriteString("}\n\n")

	b.WriteString("// InformerFor returns the SharedIndexInformer for obj using an internal\n")
	b.WriteString("// client.\n")
	b.WriteString("func (f *sharedInformerFactory) InformerFor(obj runtime.Object, newFunc internalinterfaces.NewInformerFunc) cache.SharedIndexInformer {\n")
	b.WriteString("\tf.lock.Lock()\n")
	b.WriteString("\tdefer f.lock.Unlock()\n\n")
	b.WriteString("\tinformerType := reflect.TypeOf(obj)\n")
	b.WriteString("\tinformer, exists := f.informers[informerType]\n")
	b.WriteString("\tif exists {\n")
	b.WriteString("\t\treturn informer\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tresyncPeriod, exists := f.customResync[informerType]\n")
	b.WriteString("\tif !exists {\n")
	b.WriteString("\t\tresyncPeriod = f.defaultResync\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tinformer = newFunc(f.client, resyncPeriod)\n")
	b.WriteString("\tif f.transform != nil {\n")
	b.WriteString("\t\tinformer.SetTransform(f.transform)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tf.informers[informerType] = informer\n\n")
	b.WriteString("\treturn informer\n")
	b.WriteString("}\n\n")

	b.WriteString("// SharedInformerFactory provides shared informers for resources in all known\n")
	b.WriteString("// API group versions.\n")
	b.WriteString("type SharedInformerFactory interface {\n")
	b.WriteString("\tinternalinterfaces.SharedInformerFactory\n\n")
	b.WriteString("\tStart(stopCh <-chan struct{})\n")
	b.WriteString("\tStartWithContext(ctx context.Context)\n")
	b.WriteString("\tShutdown()\n")
	b.WriteString("\tWaitForCacheSync(stopCh <-chan struct{}) map[reflect.Type]bool\n")
	b.WriteString("\tWaitForCacheSyncWithContext(ctx context.Context) cache.SyncResult\n")
	b.WriteString("\tForResource(resource schema.GroupVersionResource) (GenericInformer, error)\n")
	b.WriteString("\tInformerFor(obj runtime.Object, newFunc internalinterfaces.NewInformerFunc) cache.SharedIndexInformer\n\n")
	for _, g := range s.Groups {
		fmt.Fprintf(&b, "\t%s() %s.Interface\n", g.GroupGoName, groupPkgName(g))
	}
	b.WriteString("}\n\n")

	for _, g := range s.Groups {
		fmt.Fprintf(&b, "func (f *sharedInformerFactory) %s() %s.Interface {\n", g.GroupGoName, groupPkgName(g))
		fmt.Fprintf(&b, "\treturn %s.New(f, f.namespace, f.tweakListOptions)\n", groupPkgName(g))
		b.WriteString("}\n\n")
	}

	return b.String()
}
