// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Package informer generates the informers/ subtree (factory, group/version
// interfaces, per-resource informers) in the client-go style.
package informer

import (
	"strings"

	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/spec"
)

// groupPkgName returns the directory name for a group, e.g. "apps" or "core".
func groupPkgName(g *spec.GroupSpec) string {
	if g.Group == "" {
		return "core"
	}
	return g.Group
}

// versionGoName returns the exported Go name for a version, e.g. "V1".
func versionGoName(vs *spec.VersionSpec) string {
	return upperFirst(vs.Version)
}

// apiAlias returns the API types import alias, e.g. "appsv1".
func apiAlias(g *spec.GroupSpec, vs *spec.VersionSpec) string {
	return strings.ToLower(g.GroupGoName) + vs.Version
}

// apiAliasWithPrefix returns the API types alias used inside informer files,
// e.g. "apiappsv1", to avoid colliding with the lister package alias.
func apiAliasWithPrefix(g *spec.GroupSpec, vs *spec.VersionSpec) string {
	return "api" + apiAlias(g, vs)
}

// informersRoot returns the import path of the informers package.
func informersRoot(s *spec.Spec) string {
	return s.ClientsetGoPackage + "/informers"
}

// groupInformerPath returns the import path of a group's informer package.
func groupInformerPath(s *spec.Spec, g *spec.GroupSpec) string {
	return informersRoot(s) + "/" + groupPkgName(g)
}

// versionInformerPath returns the import path of a group/version informer
// package.
func versionInformerPath(s *spec.Spec, g *spec.GroupSpec, vs *spec.VersionSpec) string {
	return groupInformerPath(s, g) + "/" + vs.Version
}

// listerPath returns the import path of a group/version lister package.
func listerPath(s *spec.Spec, g *spec.GroupSpec, vs *spec.VersionSpec) string {
	return s.ClientsetGoPackage + "/listers/" + groupPkgName(g) + "/" + vs.Version
}

const header = `// Code generated by protoc-gen-onexmesh-client. DO NOT EDIT.

`

func upperFirst(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func lowerFirst(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}
