// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// The onexmesh errno extensions let a proto enum double as a semantic error
// catalog: an enum value carries an HTTP status code, and the protoc-gen-errno
// plugin turns each value into an errorsx constructor + Reason constant.
//
// Extension field numbers live in the reserved custom-option range (>= 50000)
// so they never collide with other well-known extensions.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: errno.proto

package errno

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_errno_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         51234,
		Name:          "onexmesh.errno.v1.default_code",
		Tag:           "varint,51234,opt,name=default_code",
		Filename:      "errno.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         51235,
		Name:          "onexmesh.errno.v1.code",
		Tag:           "varint,51235,opt,name=code",
		Filename:      "errno.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// default_code is the HTTP status code applied to every enum value that does
	// not set its own code.
	//
	// optional int32 default_code = 51234;
	E_DefaultCode = &file_errno_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// code is the HTTP status code for a single enum value.
	//
	// optional int32 code = 51235;
	E_Code = &file_errno_proto_extTypes[1]
)

var File_errno_proto protoreflect.FileDescriptor

const file_errno_proto_rawDesc = "" +
	"\n" +
	"\verrno.proto\x12\x11onexmesh.errno.v1\x1a google/protobuf/descriptor.proto:A\n" +
	"\fdefault_code\x12\x1c.google.protobuf.EnumOptions\x18\xa2\x90\x03 \x01(\x05R\vdefaultCode:7\n" +
	"\x04code\x12!.google.protobuf.EnumValueOptions\x18\xa3\x90\x03 \x01(\x05R\x04codeB/Z-github.com/onexstack/onexmesh/pkg/errno;errnob\x06proto3"

var file_errno_proto_goTypes = []any{
	(*descriptorpb.EnumOptions)(nil),      // 0: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_errno_proto_depIdxs = []int32{
	0, // 0: onexmesh.errno.v1.default_code:extendee -> google.protobuf.EnumOptions
	1, // 1: onexmesh.errno.v1.code:extendee -> google.protobuf.EnumValueOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errno_proto_init() }
func file_errno_proto_init() {
	if File_errno_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errno_proto_rawDesc), len(file_errno_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_errno_proto_goTypes,
		DependencyIndexes: file_errno_proto_depIdxs,
		ExtensionInfos:    file_errno_proto_extTypes,
	}.Build()
	File_errno_proto = out.File
	file_errno_proto_goTypes = nil
	file_errno_proto_depIdxs = nil
}
