// Copyright 2026 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Package meta generates the zz_generated.meta.go adapter that makes a
// generated proto message satisfy runtime.Object and metav1.Object, the type
// constraints required by k8s.io/client-go/gentype.
package meta

import (
	"fmt"
	"strings"

	"github.com/onexstack/onexmesh/cmd/protoc-gen-onexmesh-client/internal/spec"
)

// Generate renders the full zz_generated.meta.go for a group/version.
func Generate(vs *spec.VersionSpec) string {
	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "package %s\n\n", vs.GoPackageName)
	b.WriteString(imports)

	for _, rs := range vs.Resources {
		generateObject(&b, rs)
		generateList(&b, rs)
	}
	generateListMetaAdapter(&b, vs)
	return b.String()
}

const header = `// Code generated by protoc-gen-onexmesh-client. DO NOT EDIT.

`

const imports = `import (
	proto "google.golang.org/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"

	meshmeta "github.com/onexstack/onexmesh/pkg/proto/onexmesh/meta/v1"
)

`

// generateObject renders the runtime.Object + metav1.Object adapter for a
// resource object type.
func generateObject(b *strings.Builder, rs *spec.ResourceSpec) {
	k := rs.Kind
	av, kf, mf := rs.APIVersionField, rs.KindField, rs.MetadataField

	fmt.Fprintf(b, "// %s implements runtime.Object and metav1.Object.\n", k)
	fmt.Fprintf(b, "var _ runtime.Object = &%s{}\n", k)
	fmt.Fprintf(b, "var _ metav1.Object = &%s{}\n\n", k)

	// runtime.Object: ObjectKind.
	fmt.Fprintf(b, "func (in *%s) GetObjectKind() schema.ObjectKind { return in }\n\n", k)
	fmt.Fprintf(b, "func (in *%s) GroupVersionKind() schema.GroupVersionKind {\n", k)
	fmt.Fprintf(b, "\treturn schema.FromAPIVersionAndKind(in.%s, in.%s)\n", av, kf)
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "func (in *%s) SetGroupVersionKind(gvk schema.GroupVersionKind) {\n", k)
	fmt.Fprintf(b, "\tin.%s, in.%s = gvk.ToAPIVersionAndKind()\n", av, kf)
	b.WriteString("}\n\n")

	// runtime.Object: DeepCopyObject.
	fmt.Fprintf(b, "func (in *%s) DeepCopyObject() runtime.Object {\n", k)
	fmt.Fprintf(b, "\treturn proto.Clone(in).(*%s)\n", k)
	b.WriteString("}\n\n")

	// metav1.Object: string fields.
	for _, f := range []struct{ suffix, field string }{
		{"Name", "Name"},
		{"GenerateName", "GenerateName"},
		{"Namespace", "Namespace"},
		{"SelfLink", "SelfLink"},
		{"ResourceVersion", "ResourceVersion"},
	} {
		generateStringField(b, k, mf, f.suffix, f.field)
	}

	// metav1.Object: UID (string <-> types.UID).
	fmt.Fprintf(b, "func (in *%s) GetUID() types.UID {\n", k)
	fmt.Fprintf(b, "\tif in.%s != nil { return types.UID(in.%s.Uid) }\n", mf, mf)
	b.WriteString("\treturn \"\"\n}\n\n")
	fmt.Fprintf(b, "func (in *%s) SetUID(uid types.UID) {\n", k)
	fmt.Fprintf(b, "\tif in.%s == nil { in.%s = &meshmeta.ObjectMeta{} }\n", mf, mf)
	fmt.Fprintf(b, "\tin.%s.Uid = string(uid)\n", mf)
	b.WriteString("}\n\n")

	// metav1.Object: generation (int64).
	fmt.Fprintf(b, "func (in *%s) GetGeneration() int64 {\n", k)
	fmt.Fprintf(b, "\tif in.%s != nil { return in.%s.Generation }\n", mf, mf)
	b.WriteString("\treturn 0\n}\n\n")
	fmt.Fprintf(b, "func (in *%s) SetGeneration(generation int64) {\n", k)
	fmt.Fprintf(b, "\tif in.%s == nil { in.%s = &meshmeta.ObjectMeta{} }\n", mf, mf)
	fmt.Fprintf(b, "\tin.%s.Generation = generation\n", mf)
	b.WriteString("}\n\n")

	// metav1.Object: creation/deletion timestamps (timestamppb <-> metav1.Time).
	fmt.Fprintf(b, "func (in *%s) GetCreationTimestamp() metav1.Time {\n", k)
	fmt.Fprintf(b, "\tif in.%s != nil && in.%s.CreationTimestamp != nil { return metav1.Time{Time: in.%s.CreationTimestamp.AsTime()} }\n", mf, mf, mf)
	b.WriteString("\treturn metav1.Time{}\n}\n\n")
	fmt.Fprintf(b, "func (in *%s) SetCreationTimestamp(timestamp metav1.Time) {\n", k)
	fmt.Fprintf(b, "\tif in.%s == nil { in.%s = &meshmeta.ObjectMeta{} }\n", mf, mf)
	fmt.Fprintf(b, "\tin.%s.CreationTimestamp = timestamppb.New(timestamp.Time)\n", mf)
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "func (in *%s) GetDeletionTimestamp() *metav1.Time {\n", k)
	fmt.Fprintf(b, "\tif in.%s != nil && in.%s.DeletionTimestamp != nil { return &metav1.Time{Time: in.%s.DeletionTimestamp.AsTime()} }\n", mf, mf, mf)
	b.WriteString("\treturn nil\n}\n\n")
	fmt.Fprintf(b, "func (in *%s) SetDeletionTimestamp(timestamp *metav1.Time) {\n", k)
	fmt.Fprintf(b, "\tif in.%s == nil { in.%s = &meshmeta.ObjectMeta{} }\n", mf, mf)
	fmt.Fprintf(b, "\tif timestamp != nil { in.%s.DeletionTimestamp = timestamppb.New(timestamp.Time) } else { in.%s.DeletionTimestamp = nil }\n", mf, mf)
	b.WriteString("}\n\n")

	// metav1.Object: deletionGracePeriodSeconds (*int64).
	fmt.Fprintf(b, "func (in *%s) GetDeletionGracePeriodSeconds() *int64 {\n", k)
	fmt.Fprintf(b, "\tif in.%s != nil { return in.%s.DeletionGracePeriodSeconds }\n", mf, mf)
	b.WriteString("\treturn nil\n}\n\n")
	fmt.Fprintf(b, "func (in *%s) SetDeletionGracePeriodSeconds(seconds *int64) {\n", k)
	fmt.Fprintf(b, "\tif in.%s == nil { in.%s = &meshmeta.ObjectMeta{} }\n", mf, mf)
	fmt.Fprintf(b, "\tin.%s.DeletionGracePeriodSeconds = seconds\n", mf)
	b.WriteString("}\n\n")

	// metav1.Object: labels/annotations (map).
	for _, f := range []struct{ suffix, field string }{
		{"Labels", "Labels"},
		{"Annotations", "Annotations"},
	} {
		fmt.Fprintf(b, "func (in *%s) Get%s() map[string]string {\n", k, f.suffix)
		fmt.Fprintf(b, "\tif in.%s != nil { return in.%s.%s }\n", mf, mf, f.field)
		b.WriteString("\treturn nil\n}\n\n")
		fmt.Fprintf(b, "func (in *%s) Set%s(%s map[string]string) {\n", k, f.suffix, lowerFirst(f.suffix))
		fmt.Fprintf(b, "\tif in.%s == nil { in.%s = &meshmeta.ObjectMeta{} }\n", mf, mf)
		fmt.Fprintf(b, "\tin.%s.%s = %s\n", mf, f.field, lowerFirst(f.suffix))
		b.WriteString("}\n\n")
	}

	// metav1.Object: finalizers ([]string).
	fmt.Fprintf(b, "func (in *%s) GetFinalizers() []string {\n", k)
	fmt.Fprintf(b, "\tif in.%s != nil { return in.%s.Finalizers }\n", mf, mf)
	b.WriteString("\treturn nil\n}\n\n")
	fmt.Fprintf(b, "func (in *%s) SetFinalizers(finalizers []string) {\n", k)
	fmt.Fprintf(b, "\tif in.%s == nil { in.%s = &meshmeta.ObjectMeta{} }\n", mf, mf)
	fmt.Fprintf(b, "\tin.%s.Finalizers = finalizers\n", mf)
	b.WriteString("}\n\n")

	// metav1.Object: ownerReferences / managedFields (omitted, return empty).
	fmt.Fprintf(b, "func (in *%s) GetOwnerReferences() []metav1.OwnerReference { return nil }\n\n", k)
	fmt.Fprintf(b, "func (in *%s) SetOwnerReferences(references []metav1.OwnerReference) {}\n\n", k)
	fmt.Fprintf(b, "func (in *%s) GetManagedFields() []metav1.ManagedFieldsEntry { return nil }\n\n", k)
	fmt.Fprintf(b, "func (in *%s) SetManagedFields(managedFields []metav1.ManagedFieldsEntry) {}\n\n", k)
}

func generateStringField(b *strings.Builder, k, mf, suffix, field string) {
	fmt.Fprintf(b, "func (in *%s) Get%s() string {\n", k, suffix)
	fmt.Fprintf(b, "\tif in.%s != nil { return in.%s.%s }\n", mf, mf, field)
	b.WriteString("\treturn \"\"\n}\n\n")
	fmt.Fprintf(b, "func (in *%s) Set%s(%s string) {\n", k, suffix, lowerFirst(suffix))
	fmt.Fprintf(b, "\tif in.%s == nil { in.%s = &meshmeta.ObjectMeta{} }\n", mf, mf)
	fmt.Fprintf(b, "\tin.%s.%s = %s\n", mf, field, lowerFirst(suffix))
	b.WriteString("}\n\n")
}

// generateList renders the runtime.Object adapter for a list type.
func generateList(b *strings.Builder, rs *spec.ResourceSpec) {
	if rs.ListKind == "" {
		return
	}
	k := rs.ListKind
	av, kf, mf := rs.APIVersionField, rs.KindField, rs.MetadataField

	fmt.Fprintf(b, "// %s implements runtime.Object and metav1.ListMetaAccessor.\n", k)
	fmt.Fprintf(b, "var _ runtime.Object = &%s{}\n", k)
	fmt.Fprintf(b, "var _ metav1.ListMetaAccessor = &%s{}\n\n", k)
	fmt.Fprintf(b, "func (in *%s) GetObjectKind() schema.ObjectKind { return in }\n\n", k)
	fmt.Fprintf(b, "func (in *%s) GroupVersionKind() schema.GroupVersionKind {\n", k)
	fmt.Fprintf(b, "\treturn schema.FromAPIVersionAndKind(in.%s, in.%s)\n", av, kf)
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "func (in *%s) SetGroupVersionKind(gvk schema.GroupVersionKind) {\n", k)
	fmt.Fprintf(b, "\tin.%s, in.%s = gvk.ToAPIVersionAndKind()\n", av, kf)
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "func (in *%s) DeepCopyObject() runtime.Object {\n", k)
	fmt.Fprintf(b, "\treturn proto.Clone(in).(*%s)\n", k)
	b.WriteString("}\n\n")
	// GetListMeta satisfies metav1.ListMetaAccessor.
	fmt.Fprintf(b, "func (in *%s) GetListMeta() metav1.ListInterface {\n", k)
	fmt.Fprintf(b, "\tif in.%s == nil { in.%s = &meshmeta.ListMeta{} }\n", mf, mf)
	fmt.Fprintf(b, "\treturn &meshListMetaAdapter{in.%s}\n", mf)
	b.WriteString("}\n\n")
}

// generateListMetaAdapter renders the shared adapter that makes
// *meshmeta.ListMeta satisfy metav1.ListInterface. It is generated once per
// package (shared by all list types) and accesses the ListMeta fields
// directly, avoiding the signature clash between protoc-gen-go's
// GetRemainingItemCount() int64 getter and ListInterface's *int64 form.
func generateListMetaAdapter(b *strings.Builder, vs *spec.VersionSpec) {
	hasList := false
	for _, rs := range vs.Resources {
		if rs.ListKind != "" {
			hasList = true
			break
		}
	}
	if !hasList {
		return
	}

	b.WriteString("// meshListMetaAdapter adapts *meshmeta.ListMeta to metav1.ListInterface.\n")
	b.WriteString("type meshListMetaAdapter struct {\n\tm *meshmeta.ListMeta\n}\n\n")
	b.WriteString("func (a *meshListMetaAdapter) GetResourceVersion() string {\n\tif a.m != nil { return a.m.ResourceVersion }\n\treturn \"\"\n}\n\n")
	b.WriteString("func (a *meshListMetaAdapter) SetResourceVersion(v string) {\n\tif a.m != nil { a.m.ResourceVersion = v }\n}\n\n")
	b.WriteString("func (a *meshListMetaAdapter) GetSelfLink() string { return \"\" }\n\n")
	b.WriteString("func (a *meshListMetaAdapter) SetSelfLink(v string) {}\n\n")
	b.WriteString("func (a *meshListMetaAdapter) GetContinue() string {\n\tif a.m != nil { return a.m.Continue }\n\treturn \"\"\n}\n\n")
	b.WriteString("func (a *meshListMetaAdapter) SetContinue(v string) {\n\tif a.m != nil { a.m.Continue = v }\n}\n\n")
	b.WriteString("func (a *meshListMetaAdapter) GetRemainingItemCount() *int64 {\n\tif a.m != nil { return a.m.RemainingItemCount }\n\treturn nil\n}\n\n")
	b.WriteString("func (a *meshListMetaAdapter) SetRemainingItemCount(v *int64) {\n\tif a.m != nil { a.m.RemainingItemCount = v }\n}\n")
}

func lowerFirst(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}
